### ISSUE TITLE
crash in the onSdkInitialized

### ISSUE THREAD

**Issue by batikansosun** [AppLovin/AppLovin-MAX-SDK-Android#120]
Hi there,

I migrated ads SDK from Mopub to Applovin last week. I am facing a crash and I added the crash trace below. Looking forward to your help.

Caused by: kotlin.KotlinNullPointerException: 	at com.bla.bla.fragments.HomeFragment.initAds(Unknown Source:76)
	at com.bla.bla.activities.MainActivity.c(:1)
	at com.bla.bla.activities.MainActivity$c.onSdkInitialized(Unknown Source:2)
	at com.applovin.impl.sdk.m$1.run(Unknown Source:8)
	at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:8)
	at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:1)
	at com.applovin.impl.sdk.m.a(Unknown Source:13)
	at com.applovin.sdk.AppLovinSdk.initializeSdk(Unknown Source:2)
	at com.bla.bla.activities.MainActivity.onCreate(Unknown Source:43)
	at android.app.Activity.performCreate(Activity.java:8146)
	at android.app.Activity.performCreate(Activity.java:8130)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3689)

**Comment by chauduyphanvu** [comment]
@batikansosun, could you show your code snippets as well (the stack trace is referencing your code right before the crash). Thanks.

Vu Chau
AppLovin Team

**Comment by mrpuzzler** [comment]
Approx same crash with latest 11.0 version

FATAL EXCEPTION: main
    Process: com.xxx.mundus, PID: 2686
    java.lang.NullPointerException
        at com.applovin.impl.mediation.e.a(Unknown Source)
        at com.applovin.impl.mediation.e.a(Unknown Source)
        at com.applovin.impl.mediation.MediationServiceImpl.collectSignal(Unknown Source)
        at com.applovin.impl.mediation.b.b$2.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by mrpuzzler** [comment]
AppLovinSdk: [Utils] Failed to process version string.
    java.lang.NumberFormatException: Invalid int: ""
        at java.lang.Integer.invalidInt(Integer.java:137)
        at java.lang.Integer.parseInt(Integer.java:358)
        at java.lang.Integer.parseInt(Integer.java:331)
        at com.applovin.impl.sdk.utils.Utils.compare(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.b.a.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.b.b.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.b.b.<init>(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.b.a$1.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.b.a$1.a(Unknown Source)
        at com.applovin.impl.sdk.e.u$1.a(Unknown Source)
        at com.applovin.impl.sdk.network.b.a(Unknown Source)
        at com.applovin.impl.sdk.e.u.run(Unknown Source)
        at com.applovin.impl.sdk.e.o$c.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

**Comment by batikansosun** [comment]
> @batikansosun, could you show your code snippets as well (the stack trace is referencing your code right before the crash). Thanks.
> 
> Vu Chau AppLovin Team

@chauduyphanvu  hi,

I call the below method in the SDK's initializeSdk callback.

`   fun initAds(){
        adView = rootView!!.findViewById(R.id.adViewHomeList)
        adView!!.setListener(this)
        adView!!.loadAd()

        adView2 = rootView!!.findViewById(R.id.adViewHomeList2)
        adView2!!.setListener(this)
        adView2!!.loadAd()
    }`

**Comment by mrpuzzler** [comment]
Nothing special. Init sdk with default code.

Пт, 28 янв. 2022 г. в 16:00, Batıkan Sosun ***@***.***>:

**Comment by chauduyphanvu** [comment]
@batikansosun, is your `rootView` null by any chance? Also make sure your `adViewHomeList` and `adViewHomeList2` are properly defined ([example](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/e51e72e23afff843a22c5e8f915f14bb6b0a4917/AppLovin%20MAX%20Demo%20App%20-%20Java/app/src/main/res/layout/activity_layout_editor_banner_ad.xml#L10-L18)).

@mrpuzzler, please see https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/88 for the discussion.

**Comment by mrpuzzler** [comment]
I run it without google service and it crashes. With google service it
works fine.

Пт, 28 янв. 2022 г. в 18:33, chauduyphanvu ***@***.***>:

**Comment by chauduyphanvu** [comment]
@mrpuzzler - since your two stack traces are different from each other (and different from the OP's trace), could you open new threads for them separately so it's easier to follow/investigate? Thanks.
