### ISSUE TITLE
AppLovinInitializer.initialize ANR

### ISSUE THREAD

**Issue by waseefakhtar** [AppLovin/AppLovin-MAX-SDK-Android#123]
Hi,

We've been seeing these 2 ANRs related with AppLovin SDK on a couple of devices and wonder if you know why this might be and if you have a solution:

```
main (waiting): tid=1 systid=8107
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:279)
       at android.app.SharedPreferencesImpl.contains(SharedPreferencesImpl.java:353)
       at com.applovin.impl.sdk.c.e.a(e.java)
       at com.applovin.impl.sdk.k.a(k.java)
       at com.applovin.impl.sdk.c.c.b(c.java)
       at com.applovin.impl.sdk.c.c.<init>(c.java)
       at com.applovin.impl.sdk.k.a(k.java)
       at com.applovin.sdk.AppLovinSdk.a(AppLovinSdk.java)
       at com.applovin.sdk.AppLovinSdk.getInstance(AppLovinSdk.java)
       at com.google.ads.mediation.applovin.AppLovinInitializer.initialize(AppLovinInitializer.java:85)
       at com.google.ads.mediation.applovin.AppLovinMediationAdapter.initialize(AppLovinMediationAdapter.java:177)
       at com.google.android.gms.internal.ads.zzbwg.zzF(zzbwg.java:15)
       at com.google.android.gms.internal.ads.zzbvj.zzbR(zzbvj.java:38)
       at com.google.android.gms.internal.ads.zzht.onTransact(zzht.java:3)
       at android.os.Binder.transact(Binder.java:1043)
       at ahm.bj(ahm.java:2)
       at com.google.android.gms.ads.internal.mediation.client.e.q(e.java)
       at com.google.android.gms.ads.nonagon.initialization.f.run(f.java:3)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at auj.a(auj.java)
       at com.google.android.gms.ads.internal.util.f.a(f.java:1)
       at auj.dispatchMessage(auj.java)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8037)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

```
main (runnable): tid=1 systid=4680
       at android.view.Display.getRealSize(Display.java:1360)
       at com.applovin.impl.sdk.utils.f.a(f.java)
       at com.applovin.sdk.AppLovinSdkUtils.isTablet(AppLovinSdkUtils.java)
       at com.applovin.impl.sdk.m.o(m.java)
       at com.applovin.impl.sdk.m.<init>(m.java)
       at com.applovin.impl.sdk.k.a(k.java)
       at com.applovin.sdk.AppLovinSdk.a(AppLovinSdk.java)
       at com.applovin.sdk.AppLovinSdk.getInstance(AppLovinSdk.java)
       at com.google.ads.mediation.applovin.AppLovinInitializer.initialize(AppLovinInitializer.java:85)
       at com.google.ads.mediation.applovin.AppLovinMediationAdapter.initialize(AppLovinMediationAdapter.java:177)
       at com.google.android.gms.internal.ads.zzbwg.zzF(zzbwg.java:15)
       at com.google.android.gms.internal.ads.zzbvj.zzbR(zzbvj.java:38)
       at com.google.android.gms.internal.ads.zzht.onTransact(zzht.java:3)
       at android.os.Binder.transact(Binder.java:1064)
       at ahm.bj(ahm.java:2)
       at com.google.android.gms.ads.internal.mediation.client.e.q(e.java)
       at com.google.android.gms.ads.nonagon.initialization.f.run(f.java:3)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at auj.a(auj.java)
       at com.google.android.gms.ads.internal.util.f.a(f.java:1)
       at auj.dispatchMessage(auj.java)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

AppLovin SDK Version: 10.3.3.0

<img src="https://user-images.githubusercontent.com/4093820/151592397-41a3cb9d-3ca4-4c43-8394-30f4f98bdffc.png" width="300"/>

**Comment by Lorenzo45** [comment]
Hi @waseefakhtar - Would you be able to share the AppLovin SDK version you're using? Also what's the severity of these ANRs?

**Comment by waseefakhtar** [comment]
> Hi @waseefakhtar - Would you be able to share the AppLovin SDK version you're using? Also what's the severity of these ANRs?

The version is 10.3.3.0. They're not a lot but I see a few of them in each of our versions which are reported as separated issues.

<img src="https://user-images.githubusercontent.com/4093820/151598989-71137f28-799c-4593-9807-825e7da4c66a.png" width="400"/>

**Comment by Lorenzo45** [comment]
Thanks for bringing these to our attention. The main reason these ANRs are occurring is because AdMob is initializing our SDK on the main thread. We'd recommend initializing our SDK on a background thread if possible. Let us know if these ANRs become more frequent and we'll look into potential fixes on our end.
