### ISSUE TITLE
 App crash com.applovin.impl.sdk.utils.Utils.showAlert

### ISSUE THREAD

**Issue by hoanghiephui** [AppLovin/AppLovin-MAX-SDK-Android#127]
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1444)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:469)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:114)
        at android.app.Dialog.show(Dialog.java:505)
        at com.applovin.impl.sdk.utils.Utils.showAlert(Unknown Source:25)
        at com.applovin.impl.mediation.b.e$1.run(Unknown Source:16)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by thomasmso** [comment]
Hi @hoanghiephui - Could you tell us what version of our SDK you are experiencing this crash on?

**Comment by hoanghiephui** [comment]
> Hi @hoanghiephui - Could you tell us what version of our SDK you are experiencing this crash on?

Hi @thomasmso 
The problem occurs on version 11.1.0

**Comment by thomasmso** [comment]
Hi @hoanghiephui - This crash shouldn't affect your live builds, it should only affect your local device when you have test mode enabled. We will fix it in the next SDK release.

**Comment by thomasmso** [comment]
We just released Android SDK v11.1.1 which addresses the issue. Thank you for your feedback!

**Comment by harisEshaafi** [comment]
i am still facing this issue in version 12.6.0
