### ISSUE TITLE
Vungle adapter throwing error 

### ISSUE THREAD

**Issue by maxakash** [AppLovin/AppLovin-MAX-SDK-Android#132]
I am getting the following error while using Vungle as an ad source
Here is the logcat

```
D/AssetDownloader: Response code: 200 com.vungle.warren.downloader.DownloadRequestMediator@ac6ca4e
E/FileUtility: Cannot delete hFKaP_W3MUQmfZwym2qkzm-CkQbTNJ7vZS3FnRtOC1o=
    java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.weaponoid.miband6/no_backup/vungle_cache/clever_cache/assets/hFKaP_W3MUQmfZwym2qkzm-CkQbTNJ7vZS3FnRtOC1o=
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at com.vungle.warren.utility.FileUtility.deleteAndLogIfFailed(FileUtility.java:139)
        at com.vungle.warren.downloader.AssetDownloader.deleteFileAndMeta(AssetDownloader.java:1470)
        at com.vungle.warren.downloader.AssetDownloader.access$1500(AssetDownloader.java:74)
        at com.vungle.warren.downloader.AssetDownloader$2.run(AssetDownloader.java:457)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
E/ignored: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
E/FileUtility: Cannot delete DC5EJALYAOJ1WhGDzJdjBXCkwJlh9Rdj6WbOdDZ6HDs=
    java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.weaponoid.miband6/no_backup/vungle_cache/clever_cache/assets/DC5EJALYAOJ1WhGDzJdjBXCkwJlh9Rdj6WbOdDZ6HDs=
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at com.vungle.warren.utility.FileUtility.deleteAndLogIfFailed(FileUtility.java:139)
        at com.vungle.warren.downloader.AssetDownloader.deleteFileAndMeta(AssetDownloader.java:1470)
        at com.vungle.warren.downloader.AssetDownloader.access$1500(AssetDownloader.java:74)
        at com.vungle.warren.downloader.AssetDownloader$2.run(AssetDownloader.java:457)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
E/FileUtility: Cannot delete hFKaP_W3MUQmfZwym2qkzm-CkQbTNJ7vZS3FnRtOC1o=.vng_meta
    java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.weaponoid.miband6/no_backup/vungle_cache/clever_cache/assets/meta/hFKaP_W3MUQmfZwym2qkzm-CkQbTNJ7vZS3FnRtOC1o=.vng_meta
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at com.vungle.warren.utility.FileUtility.deleteAndLogIfFailed(FileUtility.java:139)
        at com.vungle.warren.downloader.AssetDownloader.deleteFileAndMeta(AssetDownloader.java:1473)
        at com.vungle.warren.downloader.AssetDownloader.access$1500(AssetDownloader.java:74)
        at com.vungle.warren.downloader.AssetDownloader$2.run(AssetDownloader.java:457)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
E/FileUtility: Cannot delete DC5EJALYAOJ1WhGDzJdjBXCkwJlh9Rdj6WbOdDZ6HDs=.vng_meta
    java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.weaponoid.miband6/no_backup/vungle_cache/clever_cache/assets/meta/DC5EJALYAOJ1WhGDzJdjBXCkwJlh9Rdj6WbOdDZ6HDs=.vng_meta
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at com.vungle.warren.utility.FileUtility.deleteAndLogIfFailed(FileUtility.java:139)
        at com.vungle.warren.downloader.AssetDownloader.deleteFileAndMeta(AssetDownloader.java:1473)
        at com.vungle.warren.downloader.AssetDownloader.access$1500(AssetDownloader.java:74)
        at com.vungle.warren.downloader.AssetDownloader$2.run(AssetDownloader.java:457)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
E/FileUtility: Cannot delete hFKaP_W3MUQmfZwym2qkzm-CkQbTNJ7vZS3FnRtOC1o=.vng_meta
    java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.weaponoid.miband6/no_backup/vungle_cache/clever_cache/assets/meta/hFKaP_W3MUQmfZwym2qkzm-CkQbTNJ7vZS3FnRtOC1o=.vng_meta
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at com.vungle.warren.utility.FileUtility.deleteAndLogIfFailed(FileUtility.java:139)
        at com.vungle.warren.downloader.AssetDownloader$2.run(AssetDownloader.java:460)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
E/FileUtility: Cannot delete DC5EJALYAOJ1WhGDzJdjBXCkwJlh9Rdj6WbOdDZ6HDs=.vng_meta
    java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.weaponoid.miband6/no_backup/vungle_cache/clever_cache/assets/meta/DC5EJALYAOJ1WhGDzJdjBXCkwJlh9Rdj6WbOdDZ6HDs=.vng_meta
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at com.vungle.warren.utility.FileUtility.deleteAndLogIfFailed(FileUtility.java:139)
        at com.vungle.warren.downloader.AssetDownloader$2.run(AssetDownloader.java:460)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

```

Please look into it.

**Comment by NanaAmoah** [comment]
Hi @maxakash when do you encounter this error? E.g., does this happen when you start the app ? Does this happen with a specific ad format; when you try to load or show an ad??

**Comment by NanaAmoah** [comment]
> Hi @maxakash when do you encounter this error? E.g., does this happen when you start the app ? Does this happen with a specific ad format; when you try to load or show an ad??

I understand you're getting an error when trying to use Vungle. Could you tell me more based on the questions above ?

**Comment by maxakash** [comment]
> > Hi @maxakash when do you encounter this error? E.g., does this happen when you start the app ? Does this happen with a specific ad format; when you try to load or show an ad??
> 
> I understand you're getting an error when trying to use Vungle. Could you tell me more based on the questions above ?

No, I have removed Vungle adapter. Even without vungle I am facing the issue.

**Comment by thomasmso** [comment]
The exception  being mentioned in the issue is a handled exception within Vungle's SDK, and should not result in any anomaly or loss of functionality. They will improve this in our future release to hide this, as otherwise like in this case it might create some false alarms.

If you are still facing the issue, please send stack traces, as the stack traces above all have Vungle's SDK in it.
