### ISSUE TITLE
Can not load Native Ad - invalid format

### ISSUE THREAD

**Issue by Zozulinsky** [AppLovin/AppLovin-MAX-SDK-Android#133]
Hello! I can not load native ad. Can you please tell me what the problem could be?
```
2022-02-03 14:20:27.359 E: [ListenerCallbackInvoker] Unable to notify ad event listener about ad being loaded
    java.lang.IllegalArgumentException: Attempting to render MAX native ad with invalid format: custom_template_1
        at com.applovin.mediation.nativeAds.MaxNativeAdView.a(Unknown Source:49)
        at com.applovin.mediation.nativeAds.MaxNativeAdView.<init>(Unknown Source:31)
        at com.applovin.mediation.nativeAds.MaxNativeAdView.<init>(Unknown Source:74)
        at com.applovin.mediation.nativeAds.MaxNativeAdView.<init>(Unknown Source:1)
        at com.applovin.impl.mediation.ads.MaxNativeAdLoaderImpl$a$1.run(Unknown Source:63)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:8)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:1)
        at com.applovin.impl.mediation.ads.MaxNativeAdLoaderImpl$a.onAdLoaded(Unknown Source:5)
        at com.applovin.impl.mediation.d$a.onAdLoaded(Unknown Source:49)
        at com.applovin.impl.sdk.utils.i$7.run(Unknown Source:4)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:8)
        at com.applovin.impl.sdk.utils.i.a(Unknown Source:9)
        at com.applovin.impl.sdk.utils.i.a(Unknown Source:1)
        at com.applovin.impl.mediation.b.e.a(Unknown Source:141)
        at com.applovin.impl.mediation.b.e.a(Unknown Source:0)
        at com.applovin.impl.mediation.b.e$a$1.onAdLoaded(Unknown Source:113)
        at com.applovin.impl.sdk.utils.i$7.run(Unknown Source:4)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:8)
        at com.applovin.impl.sdk.utils.i.a(Unknown Source:9)
        at com.applovin.impl.sdk.utils.i.a(Unknown Source:1)
        at com.applovin.impl.mediation.MediationServiceImpl$a.a(Unknown Source:19)
        at com.applovin.impl.mediation.g$a$1.run(Unknown Source:32)
        at com.applovin.impl.mediation.g$a$14.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by maxakash** [comment]
Hey @Zozulinsky, I faced this  issue too, this usually happens if you have created a new ad unit or you have switched between small, large or manual native ad type.
I was able to overcome it by waiting for some time .

**Comment by Zozulinsky** [comment]
@maxakash How long have you waited?

**Comment by maxakash** [comment]
> @maxakash How long have you waited?
I tried again next morning and it worked.

**Comment by Zozulinsky** [comment]
Oh, i wrong created MaxNativeAdView. Need create MaxNativeAdView when called loadAd each time

**Comment by chauduyphanvu** [comment]
@Zozulinsky - looks like you've figured it out on your own! I'm closing this issue now - feel free to open a separate thread if you need something else.

Vu Chau
AppLovin Team
