### ISSUE TITLE
Fatal Exception: int android.view.View.getVisibility() NullPointerException

### ISSUE THREAD

**Issue by billyking991** [AppLovin/AppLovin-MAX-SDK-Android#150]
I've updated three completely different apps to AppLovin MAX from MoPub in the last three weeks. I'm suddenly getting a new crash in each app, each with an identical stack trace.  This crash was not happening prior to the migration.

There isn't anything (that I can tell) in the stack trace that points to AppLovin MAX specifically, but I've only changed the mediation platform and the apps are completely different from one another.  After quite a bit of digging, I've concluded that it has to have something to do with the AppLovin MAX implementation.  Any ideas?

Details:
Occurs on Android 10, 11, and 12.
Occurs 99% - 100% in the foreground.
Occurs on both 11.0.0 and 11.1.0 (from what I can tell).
Ad Companies in my mediation Scheme:  AdMob, Facebook, InMobi, Vungle, Smaato, and AdColony
Devices: Mostly Samsung and Pixel phones, but a few other device brands are listed.  I don't see any tablets represented in Crashlytics, but most of my apps run mainly on phones.

Please let me know if you need any other information.  

Stack Trace:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1100)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1099)
       at android.view.View.layout(View.java:23750)
       at android.view.ViewGroup.layout(ViewGroup.java:7277)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3709)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3161)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2222)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9123)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
       at android.view.Choreographer.doCallbacks(Choreographer.java:797)
       at android.view.Choreographer.doFrame(Choreographer.java:732)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by chauduyphanvu** [comment]
@billyking991, thanks for the report. This is not something we have seen before, either!

Are you able to log / share details about what your apps are doing (initializing AppLovin MAX, requesting ads, showing ads, etc.) before the time of the crash? If your integration isn't too big, you could also try replicating your ad logic in [our sample app](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/tree/master/AppLovin%20MAX%20Demo%20App%20-%20Java).

Vu Chau
AppLovin Team

**Comment by billyking991** [comment]
Hi Vu,

Thank you for getting back to me.  I appreciate the response.  

Unfortunately, I'm only able to see the crash on Firebase and in the Google Play console.  I have 14 separate test devices, but so far have been unable to reproduce it.  Let me go through the logic of the test project and see if I can figure out what I'm doing differently.  Please give me a few days to try and figure this out.  I just wanted to make you aware of what is going on.  

Again, the only reason I think it could be due to the MAX SDK is because of my three separate apps and this crash only started after the MAX implementation.  I've used MoPub for about 6 years, so this is the first time I've tried another mediation source.

Thank you,
Billy King

**Comment by chauduyphanvu** [comment]
@billyking991, yes I remember you from a few MoPub issues you reported over the years (thanks for being a loyal customer!). Glad you picked MAX for your next integration. 

Sounds good - let us know when you can. I'll go through the codebase to see where we can preemptively patch against this NPE.

**Comment by billyking991** [comment]
Of course.  MAX was recommended to me as the way to go.  

This is now the most represented crash in my app.  I've rolled the MAX version out to 1 percent of users and it's crashed 7 times with the same stack trace as above.  I'm going through the examples you've provided now.

**Comment by billyking991** [comment]
Hi @chauduyphanvu,

I've been digging into this issue and it's not AppLovin MAX's fault.  It was some old code In my project that should have crashed years ago, even with MoPub.  Please accept my apologies for the mistake.  I'm uploading the new app to Google now and this should be fixed.  Thank you for your help and patience!

**Comment by chauduyphanvu** [comment]
Thanks for the update, and don't be too hard on yourself!

**Comment by billyking991** [comment]
I always am.  I'm just glad I've figured it out.  Have a wonderful night.
