### ISSUE TITLE
ByteDanceMediationAdapter Crash

### ISSUE THREAD

**Issue by hoanghiephui** [AppLovin/AppLovin-MAX-SDK-Android#154]
This crash log occurs occasionally after integrating 11.1.1
java.lang.RuntimeException: Method not implemented, use 'execute'
        at com.applovin.mediation.adapters.MediationAdapterBase$ExecutorServiceAdapter.submit(Unknown Source:4)
        at com.applovin.mediation.adapters.MediationAdapterBase.createDrawableFuture(Unknown Source:9)
        at com.applovin.mediation.adapters.ByteDanceMediationAdapter$NativeAdListener$1.run(ByteDanceMediationAdapter.java:1108)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

Func crash when i used small native ad.
`{
                        // Pangle's image resource comes in the form of a URL which needs to be fetched in a non-blocking manner
                        log( "Adding native ad icon (" + nativeAd.getIcon().getImageUrl() + ") to queue to be fetched" );
                        iconDrawableFuture = createDrawableFuture( nativeAd.getIcon().getImageUrl(), activity.getResources() );
                    }`

**Comment by hoanghiephui** [comment]
@thomasmso why why???

**Comment by thomasmso** [comment]
@hoanghiephui - Terribly sorry for the issue, we just pushed v11.1.2 to address it.

**Comment by hoanghiephui** [comment]
> @hoanghiephui - Terribly sorry for the issue, we just pushed v11.1.2 to address it.

Thanks. The problem has been resolved.
