### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: A valid Activity is required

### ISSUE THREAD

**Issue by apshard** [AppLovin/AppLovin-MAX-SDK-Android#158]
This crash started appearing in our Crashlytics report after updating to the latest version 11.1.2
```
Fatal Exception: java.lang.IllegalArgumentException: A valid Activity is required
       at com.applovin.impl.mediation.MediationServiceImpl.loadThirdPartyMediatedAd(MediationServiceImpl.java:146)
       at com.applovin.impl.mediation.b.e$a.run(e.java:115)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by chauduyphanvu** [comment]
@apshard, we throw this exception when we receive a null Activity from the app when it's going to request for an ad from a mediated network. Could you check to see if that might be happening?

Vu Chau
AppLovin Team

**Comment by onestravel** [comment]
After updating to version 11.1.2, the following crash appeared
` java.lang.IllegalArgumentException: 
       at com.applovin.impl.mediation.MediationServiceImpl.loadThirdPartyMediatedAd(MediationServiceImpl.java:146)
       at com.applovin.impl.mediation.b.e$a.run(e.java:111)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)`

**Comment by thomasmso** [comment]
@onestravel - What ad format are you running? It looks like the SDK was not able to detect an `Activity` context in the app - would you be able to pass in one in `AppLovinSdk.getInstance(...)`?

**Comment by onestravel** [comment]
@thomasmso We use `interstitial ads` and `native ads`. Before we pass in the `Context`, we will judge whether the Context object is not null, and we will judge that the `Activity Context` is not in the state of `isFinishing` or `isDestroyed`

```
activity?.application?.let { context ->
            // Please make sure to set the mediation provider value to "max" to ensure proper functionality
            AppLovinSdk.getInstance(context).mediationProvider = "max"
            AppLovinSdk.getInstance(context).initializeSdk { configuration: AppLovinSdkConfiguration ->
                // AppLovin SDK is initialized, start loading ads
                callback?.onInitComplete()
            }
        }
```


```
 val isInitialized = context?.let { AppLovinSdk.getInstance(context).isInitialized } ?: false
```

**Comment by Zozulinsky** [comment]
I have same trouble :(

**Comment by thomasmso** [comment]
@Zozulinsky - This should've been fixed in https://github.com/AppLovin/AppLovin-MAX-SDK-Android/releases/tag/release_11_2_0, could you try again?
