### ISSUE TITLE
Native Ad ConcurrentModificationException

### ISSUE THREAD

**Issue by sebastian-hoebarth** [AppLovin/AppLovin-MAX-SDK-Android#162]
Applovin SDK is filling up my crashlytics with this. (Crash appears on all Android versions)

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
       at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
       at com.applovin.impl.sdk.utils.JsonUtils.shallowCopy(JsonUtils.java:15)
       at com.applovin.impl.sdk.nativeAd.e.a(e.java:2)
       at com.applovin.impl.sdk.nativeAd.e.adReceived(e.java:9)
       at com.applovin.impl.sdk.e.c$2.run(c.java:18)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by chauduyphanvu** [comment]
@sebastian-hoebarth, this has been resolved in the latest SDK release. Could you check that out? Thanks.

Vu Chau
AppLovin team

**Comment by sebastian-hoebarth** [comment]
@chauduyphanvu thank you for the info.
