### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException (Firebase crash)

### ISSUE THREAD

**Issue by hamza-mughal5593** [AppLovin/AppLovin-MAX-SDK-Android#175]
Applovin SDK: 11.1.2
Facebook adapter SDK: 6.8.0.3
App Status: Background
Device version: On multiple devices 
Network security config file: Added
happens: 6.1k times to 30 users

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
       at com.facebook.ads.internal.util.common.ANActivityLifecycleCallbacksListener.registerActivityCallbacks(ANActivityLifecycleCallbacksListener.java:70)
       at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:95)
       at java.lang.Thread.run(Thread.java:923)

**Comment by santoshbagadi** [comment]
Hi @hamza-mughal5593 , we have a fix for this issue in our latest Facebook mediation adapter: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/master/Facebook/CHANGELOG.md#6808

Please update to a Facebook mediation adapter version newer than 6.8.0.8 to fix this issue.

**Comment by hamza-mughal5593** [comment]
Got it thanks @santoshbagadi
