### ISSUE TITLE
Native ad loading issue: ClassCastException: com.applovin.impl.mediation.a.b 

### ISSUE THREAD

**Issue by sebastian-hoebarth** [AppLovin/AppLovin-MAX-SDK-Android#176]
Somehow since the SDK update I see this error in the log, not sure what's happening, but no native ad is loading

 implementation 'com.applovin:applovin-sdk:11.1.2'
 implementation 'com.applovin.mediation:google-ad-manager-adapter:20.5.0.5'
 implementation 'com.applovin.mediation:google-adapter:20.5.0.8'
 implementation 'com.applovin.mediation:fyber-adapter:8.1.2.1'
 implementation 'com.applovin.mediation:ironsource-adapter:7.2.0.0.0'
 implementation 'com.applovin.mediation:facebook-adapter:6.8.0.8'

`AppLovinSdk: [ListenerCallbackInvoker] Unable to notify ad event listener about ad being loaded
    java.lang.ClassCastException: com.applovin.impl.mediation.a.b cannot be cast to com.applovin.impl.mediation.a.d
        at com.applovin.impl.mediation.ads.MaxNativeAdLoaderImpl$a$1.run(Unknown Source:2)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:8)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:1)
        at com.applovin.impl.mediation.ads.MaxNativeAdLoaderImpl$a.onAdLoaded(Unknown Source:5)
        at com.applovin.impl.mediation.d$a.onAdLoaded(Unknown Source:49)
        at com.applovin.impl.sdk.utils.j$7.run(Unknown Source:4)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:8)
        at com.applovin.impl.sdk.utils.j.a(Unknown Source:9)
        at com.applovin.impl.sdk.utils.j.a(Unknown Source:1)
        at com.applovin.impl.mediation.b.e.a(Unknown Source:64)
        at com.applovin.impl.mediation.b.e.a(Unknown Source:0)
        at com.applovin.impl.mediation.b.e$a$1.onAdLoaded(Unknown Source:106)
        at com.applovin.impl.sdk.utils.j$7.run(Unknown Source:4)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:8)
        at com.applovin.impl.sdk.utils.j.a(Unknown Source:9)
        at com.applovin.impl.sdk.utils.j.a(Unknown Source:1)
        at com.applovin.impl.mediation.MediationServiceImpl$a.a(Unknown Source:19)
        at com.applovin.impl.mediation.g$a$1.run(Unknown Source:32)
        at com.applovin.impl.mediation.g$a$14.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

**Comment by sebastian-hoebarth** [comment]
It would be nice if you could give me a quick update on this, because I think I have to halt the current rollout because of this. Thank you.

**Comment by sebastian-hoebarth** [comment]
I figured out what the problem is. If you load MREC banner IDs in the native ad Waterfall this crash shows up in the log...
