### ISSUE TITLE
ByteDanceMediationAdapter error : java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by maxakash** [AppLovin/AppLovin-MAX-SDK-Android#179]
I am using bytedance adapter v4.2.5.2.2, and getting the following error in the logcat.

```
E/AppLovinSdk: [MediationAdapterWrapper] Unable to run adapter operation initialize, marking ByteDanceMediationAdapter as disabled
    java.lang.ExceptionInInitializerError
        at com.bytedance.sdk.openadsdk.core.h.a(GlobalInfo.java:76)
        at com.bytedance.sdk.openadsdk.TTAdSdk.init(TTAdSdk.java:122)
        at com.applovin.mediation.adapters.ByteDanceMediationAdapter.initialize(ByteDanceMediationAdapter.java:212)
        at com.applovin.impl.mediation.g$1.run(Unknown Source:89)
        at com.applovin.impl.mediation.g$8.run(Unknown Source:50)
        at com.applovin.impl.mediation.g.a(Unknown Source:19)
        at com.applovin.impl.mediation.g.a(Unknown Source:7)
        at com.applovin.impl.mediation.e.a(Unknown Source:132)
        at com.applovin.impl.mediation.e.a(Unknown Source:1)
        at com.applovin.impl.mediation.b.a$1.run(Unknown Source:44)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[AsyncTask #7,5,main] that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:227)
        at android.os.Handler.<init>(Handler.java:129)
        at com.bytedance.sdk.component.utils.x.<init>(WeakHandler.java:17)
        at com.bytedance.sdk.openadsdk.l.a.<init>(ActivityLifecycleListener.java:34)
        at com.bytedance.sdk.openadsdk.core.h.<init>(GlobalInfo.java:140)
        at com.bytedance.sdk.openadsdk.core.h.<clinit>(GlobalInfo.java:203)
        at com.bytedance.sdk.openadsdk.core.h.a(GlobalInfo.java:76) 
        at com.bytedance.sdk.openadsdk.TTAdSdk.init(TTAdSdk.java:122) 
        at com.applovin.mediation.adapters.ByteDanceMediationAdapter.initialize(ByteDanceMediationAdapter.java:212) 
        at com.applovin.impl.mediation.g$1.run(Unknown Source:89) 
        at com.applovin.impl.mediation.g$8.run(Unknown Source:50) 
        at com.applovin.impl.mediation.g.a(Unknown Source:19) 
        at com.applovin.impl.mediation.g.a(Unknown Source:7) 
        at com.applovin.impl.mediation.e.a(Unknown Source:132) 
        at com.applovin.impl.mediation.e.a(Unknown Source:1) 
        at com.applovin.impl.mediation.b.a$1.run(Unknown Source:44) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
```

Please look into it.

**Comment by maxakash** [comment]
Issue already reported.
