### ISSUE TITLE
ByteDanceMediationAdapter ExceptionInInitializerError

### ISSUE THREAD

**Issue by hoanghiephui** [AppLovin/AppLovin-MAX-SDK-Android#187]
Applovin SDK 11.1.2
ByteDance: 4.2.5.2.2
E/AppLovinSdk: [MediationAdapterWrapper] Unable to run adapter operation initialize, marking ByteDanceMediationAdapter as disabled
    java.lang.ExceptionInInitializerError
        at com.bytedance.sdk.openadsdk.core.h.a(GlobalInfo.java:76)
        at com.bytedance.sdk.openadsdk.TTAdSdk.init(TTAdSdk.java:122)
        at com.applovin.mediation.adapters.ByteDanceMediationAdapter.initialize(ByteDanceMediationAdapter.java:212)
        at com.applovin.impl.mediation.g$1.run(Unknown Source:89)
        at com.applovin.impl.mediation.g$8.run(Unknown Source:50)
        at com.applovin.impl.mediation.g.a(Unknown Source:19)
        at com.applovin.impl.mediation.g.a(Unknown Source:7)
        at com.applovin.impl.mediation.e.a(Unknown Source:132)
        at com.applovin.impl.mediation.e.a(Unknown Source:1)
        at com.applovin.impl.mediation.MediationServiceImpl.collectSignal(Unknown Source:58)
        at com.applovin.impl.mediation.b.b.a(Unknown Source:25)
        at com.applovin.impl.mediation.b.b.a(Unknown Source:38)
        at com.applovin.impl.mediation.b.b.run(Unknown Source:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[AsyncTask #1,5,main] that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:227)
        at android.os.Handler.<init>(Handler.java:129)
        at com.bytedance.sdk.component.utils.x.<init>(WeakHandler.java:17)
        at com.bytedance.sdk.openadsdk.l.a.<init>(ActivityLifecycleListener.java:34)
        at com.bytedance.sdk.openadsdk.core.h.<init>(GlobalInfo.java:140)
        at com.bytedance.sdk.openadsdk.core.h.<clinit>(GlobalInfo.java:203)
        at com.bytedance.sdk.openadsdk.core.h.a(GlobalInfo.java:76) 
        at com.bytedance.sdk.openadsdk.TTAdSdk.init(TTAdSdk.java:122) 
        at com.applovin.mediation.adapters.ByteDanceMediationAdapter.initialize(ByteDanceMediationAdapter.java:212) 
        at com.applovin.impl.mediation.g$1.run(Unknown Source:89) 
        at com.applovin.impl.mediation.g$8.run(Unknown Source:50) 
        at com.applovin.impl.mediation.g.a(Unknown Source:19) 
        at com.applovin.impl.mediation.g.a(Unknown Source:7) 
        at com.applovin.impl.mediation.e.a(Unknown Source:132) 
        at com.applovin.impl.mediation.e.a(Unknown Source:1) 
        at com.applovin.impl.mediation.MediationServiceImpl.collectSignal(Unknown Source:58) 
        at com.applovin.impl.mediation.b.b.a(Unknown Source:25) 
        at com.applovin.impl.mediation.b.b.a(Unknown Source:38) 
        at com.applovin.impl.mediation.b.b.run(Unknown Source:33) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)

**Comment by chauduyphanvu** [comment]
@hoanghiephui, thanks for the report. We are looking into this now.

Vu Chau
AppLovin Team

**Comment by hoanghiephui** [comment]
> @hoanghiephui, thanks for the report. We are looking into this now.
> 
> Vu Chau AppLovin Team

Hi @chauduyphanvu 
Can you tell me when will you guys fix this problem?
Thanks

**Comment by chauduyphanvu** [comment]
The team is actively fixing this. More updates soon!

**Comment by silenting** [comment]
We have also encountered this problem, how to solve it

**Comment by NanaAmoah** [comment]
Hi @hoanghiephui @silenting, we've pushed the fix server-side. Thanks!
