### ISSUE TITLE
Android 5.0 Crash

### ISSUE THREAD

**Issue by JonatasLemos** [AppLovin/AppLovin-MAX-SDK-Android#20]
Hello!
We have an app with the latest Applovin SDK version and after reading the Google pre-launch report we got the following Android 5.0 crash on P8 Lite (the only device with issues):

FATAL EXCEPTION: main
Process: com.algolstudio.mathmentalboost, PID: 19843
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.algolstudio.mathmentalboost/com.algolstudio.mathmentalboost.activity.MainActivity}: android.view.InflateException: Binary XML file line #75: Error inflating class com.applovin.adview.AppLovinAdView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
	at android.app.ActivityThread.access$1200(ActivityThread.java:152)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: android.view.InflateException: Binary XML file line #75: Error inflating class com.applovin.adview.AppLovinAdView
	at android.view.LayoutInflater.createView(LayoutInflater.java:652)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:368)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.algolstudio.mathmentalboost.activity.MainActivity.onCreate(MainActivity.java:26)
	at android.app.Activity.performCreate(Activity.java:6013)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:626)
	... 21 more
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x3040002
	at android.content.res.HwResources.getText(HwResources.java:1252)
	at android.content.res.Resources.getString(Resources.java:374)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:948)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:848)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:649)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:788)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:635)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:573)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:315)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:100)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:267)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:127)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:114)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:111)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:264)
	at android.webkit.WebView.<init>(WebView.java:548)
	at android.webkit.WebView.<init>(WebView.java:483)
	at android.webkit.WebView.<init>(WebView.java:466)
	at android.

Is there a way to get around it? Thank you!

**Comment by thomasmso** [comment]
Hi @JonatasLemos, thanks for reporting this. While we wait for our P8 Lite to arrive to better debug the issue - it seems like a side effect of how their OS custom handles our adview. A couple possible solutions could be to subclass our `AppLovinAdView` and using that in the Layout Editor, or creating and attaching the `AppLovinAdView` programmatically. Alternatively you can surround the creation with a try-catch and silently fail on this device.

**Comment by JonatasLemos** [comment]
We tried the try-catch approach and our issue was fixed. Thank you very much!
