### ISSUE TITLE
Native Ad Icon and main image not show

### ISSUE THREAD

**Issue by NiaNingXue** [AppLovin/AppLovin-MAX-SDK-Android#209]
SDK Version 11.2.0
I test applovin and facebook native ad, both not showing. And the Ad Unit I created is Native - Manual.
![微信截图_20220302135309](https://user-images.githubusercontent.com/5886258/156303580-7b71e025-05b8-469c-bde7-f735740b3272.png)

**Comment by hoanghiephui** [comment]
Same issues

**Comment by jmimohsin** [comment]
After releasing too many updates, but this issue is not resolved yet. Icon and media not coming!

**Comment by santoshbagadi** [comment]
Hi, sorry, seems to be happening on live ads as well. We'll update here when there is a fix

**Comment by shijingxing** [comment]
same issue
SDK Version：11.0.0
manual mode and the test mode is disabled

**Comment by cuiti** [comment]
Same issue. Looking forward to the update! :crossed_fingers:

**Comment by HardikMiyani** [comment]
i have this same issue 

can you tell me. which version i get  using below dependency 
implementation 'com.applovin:applovin-sdk:+@aar'

**Comment by santoshbagadi** [comment]
@HardikMiyani , we are actively working on this and this issue should only be happening when test mode is enabled. We'll update here when a fix is available.

**Comment by ihassanali259** [comment]
This issue is also happening in the live version 
![fourg_scrrenshot](https://user-images.githubusercontent.com/43772154/156878443-036c4782-ff0a-44dc-80f9-f4355906471d.jpeg)
o

**Comment by santoshbagadi** [comment]
Hi @ihassanali259 , do you by any chance have a non-manual template selected on our dashboard for this ad unit.

Selecting `Manual` should fix it on live builds.

**Comment by HardikMiyani** [comment]
> @HardikMiyani , we are actively working on this and this issue should only be happening when test mode is enabled. We'll update here when a fix is available.

any update regarding ads ?

**Comment by santoshbagadi** [comment]
@HardikMiyani , We have mostly fixed the issue, but we are still working on fixing it for `Manual` native ads that are loaded and rendered separately. We'll update this thread when we have a fix for all integration types.

**Comment by jmimohsin** [comment]
What are you doing guys? Native Ads are not working, only last month worked and again it stopped working. I am using manual native ad now and zero fill rate. And reward video ads also has 0..1% fill rate.

**Comment by xiaopei** [comment]
> 

I need this very much

**Comment by xiaopei** [comment]
I saw this on a new device that test model is disabled ,please fix it soon. It is very important to us

**Comment by xiaopei** [comment]
D/AppLovinSdk: [MaxNativeAdLoader] No native ad view to render. Returning the native ad to be rendered later.
2022-03-23 19:09:55.903 7179-7179/com.box.video.downloader D/AppLovinSdk: [MaxNativeAdLoader] render(adView=com.applovin.mediation.nativeAds.MaxNativeAdView{dbb2509 V.E...... ......I. 0,0-0,0}, ad=MediatedAd{thirdPartyAdPlacementId=native_native, adUnitId=3b608093b749dd22, format=NATIVE, networkName='APPLOVIN_EXCHANGE'})
2022-03-23 19:09:55.905 7179-7179/com.box.video.downloader D/AppLovinSdk: [VisibilityTracker] Tracking Visibility...
2022-03-23 19:09:55.905 7179-7179/com.box.video.downloader D/AppLovinSdk: [MaxNativeAdView] Created new MaxNativeAdView (com.applovin.impl.mediation.ads.b@bedb30e)
2022-03-23 19:09:55.909 7179-7179/com.box.video.downloader W/ImageView: Unable to open content: file:///data/user/0/com.box.video.downloader/files/al/d02bab49-3069-4a7b-8471-6c72fc28df0fMbiOAz9ohc2ynj53MLakOg.png
    java.io.FileNotFoundException: /data/user/0/com.box.video.downloader/files/al/d02bab49-3069-4a7b-8471-6c72fc28df0fMbiOAz9ohc2ynj53MLakOg.png: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1185)
        at android.graphics.ImageDecoder$ContentResolverSource.createImageDecoder(ImageDecoder.java:282)
        at android.graphics.ImageDecoder.decodeDrawableImpl(ImageDecoder.java:1743)
        at android.graphics.ImageDecoder.decodeDrawable(ImageDecoder.java:1736)
        at android.widget.ImageView.getDrawableFromUri(ImageView.java:1009)
        at android.widget.ImageView.resolveUri(ImageView.java:978)
        at android.widget.ImageView.setImageURI(ImageView.java:555)
        at com.applovin.mediation.nativeAds.MaxNativeAdView.b(Unknown Source:143)
        at com.applovin.mediation.nativeAds.MaxNativeAdView.render(Unknown Source:48)
        at com.applovin.impl.mediation.ads.MaxNativeAdLoaderImpl$1.run(Unknown Source:14)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:8)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:1)
        at com.applovin.impl.mediation.ads.MaxNativeAdLoaderImpl.a(Unknown Source:8)
        at com.applovin.impl.mediation.ads.MaxNativeAdLoaderImpl.render(Unknown Source:41)
        at com.applovin.mediation.nativeAds.MaxNativeAdLoader.render(Unknown Source:37)
        at org.trade.saturn.stark.demo.SecondActivity$17.onNativeAdLoaded(SecondActivity.java:724)
        at com.applovin.impl.sdk.utils.j$20.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileInputStream.<init>(FileInputStream.java:159) 
        at java.io.FileInputStream.<init>(FileInputStream.java:115) 
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1185) 
        at android.graphics.ImageDecoder$ContentResolverSource.createImageDecoder(ImageDecoder.java:282) 
        at android.graphics.ImageDecoder.decodeDrawableImpl(ImageDecoder.java:1743) 
        at android.graphics.ImageDecoder.decodeDrawable(ImageDecoder.java:1736) 
        at android.widget.ImageView.getDrawableFromUri(ImageView.java:1009) 
        at android.widget.ImageView.resolveUri(ImageView.java:978) 
        at android.widget.ImageView.setImageURI(ImageView.java:555) 
        at com.applovin.mediation.nativeAds.MaxNativeAdView.b(Unknown Source:143) 
        at com.applovin.mediation.nativeAds.MaxNativeAdView.render(Unknown Source:48) 
        at com.applovin.impl.mediation.ads.MaxNativeAdLoaderImpl$1.run(Unknown Source:14) 
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:8) 
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:1) 
        at com.applovin.impl.mediation.ads.MaxNativeAdLoaderImpl.a(Unknown Source:8) 
        at com.applovin.impl.mediation.ads.MaxNativeAdLoaderImpl.render(Unknown Source:41) 
        at com.applovin.mediation.nativeAds.MaxNativeAdLoader.render(Unknown Source:37) 
        at org.trade.saturn.stark.demo.SecondActivity$17.onNativeAdLoaded(SecondActivity.java:724) 
        at com.applovin.impl.sdk.utils.j$20.run(Unknown Source:6) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2022-03-23 19:09:55.910 7179-7179/com.box.video.downloader D/AppLovinSdk: [AppLovinNativeAd:20379349167825168] Registered views: [com.google.android.material.textview.MaterialTextView{9724be2 VFED..C.. ......ID 175,525-175,591 #7f080076 app:id/ads_title}, com.google.android.material.textview.MaterialTextView{b955b73 VFED..C.. ......ID 175,591-175,648 #7f080074 app:id/ads_summary}, com.google.android.material.button.MaterialButton{e672a30 VFED..C.. ......ID 1062,525-1370,693 #7f0800ac app:id/call_to_action}, org.trade.saturn.stark.nativead.api.NVNativeImageView{36808c5 VFED..C.. ......ID 0,0-175,175 #7f080129 app:id/icon_image_view}]
2022-03-23 19:09:55.911 7179-7179/com.box.video.downloader D/AppLovinSdk: [MaxNativeAdView] Scheduling impression for ad manually...
2022-03-23 19:09:55.911 7179-7179/com.box.video.downloader D/AppLovinSdk: [CommunicatorService] Sending "max_ad_events" message: Bundle[{network_placement=native_native, third_party_ad_placement_id=native_native, creative_id=6740900, network_name=APPLOVIN_EXCHANGE, id=06dab2f325c1e4a3fcb7bb96d10f8e5508dcca6f, type=WILL_DISPLAY, ad_format=NATIVE, max_ad_unit_id=3b608093b749dd22}]
2022-03-23 19:09:55.916 7179-7466/com.box.video.downloader I/AppLovinSdk: [ConnectionManager] Sending GET request to id=#164238258 "impression.appsflyer.com/com.gojek.app"...
2022-03-23 19:09:55.916 7179-7901/com.box.video.downloader I/AppLovinSdk: [ConnectionManager] Sending GET request to id=#1050154638 "imp-al-ap.jampp.com/imp.png"...
2022-03-23 19:09:55.919 7179-7179/com.box.video.downloader E/AppLovinSdk: [AdEventTracker:20379349167825168:jampp.com] Failed to run operation: update main view: com.applovin.impl.sdk.nativeAd.AppLovinMediaView{578314b V.E...... ......ID 0,0-0,0}
2022-03-23 19:09:55.919 7179-7179/com.box.video.downloader E/AppLovinSdk: [AdEventTracker:20379349167825168:jampp.com] Failed to run operation: track impression event
2022-03-23 19:09:55.921 7179-7905/com.box.video.downloader I/AppLovinSdk: [ConnectionManager] Sending GET request to id=#-1545657742 "prod-ms.applovin.com/1.0/event/mimp"...

**Comment by hoanghiephui** [comment]
Hi @thomasmso 
Sometimes, this issues reopen on sdk 11.3.1

**Comment by chauduyphanvu** [comment]
@hoanghiephui - could you share a screenshot + console logs? Thanks.

**Comment by chauduyphanvu** [comment]
We're investigating the issue and will post an update here once it's resolved. Stay tuned!

**Comment by santoshbagadi** [comment]
This should now be fixed for test mode as well. Please note that a valid ad unit ID is required.

**Comment by Eanam** [comment]
Hi @santoshbagadi , I have meet the same issue recently

The version of sdk is:  com.applovin:applovin-sdk:11.6.0

So i would like to know which version I should import to avoid this issue

**Comment by Eanam** [comment]
I meet this issue with test ads which is configured **Manual**.  

The key error message is `/data/user/0/{package_name}/files/al/xxx.jpeg: open failed: ENOENT (No such file or directory)` Which seem like that the SDK don't call method `mkdirs` before cache

**Comment by santoshbagadi** [comment]
Would you mind sharing full [verbose logs](https://dash.applovin.com/documentation/mediation/unity/getting-started/advanced-settings#enable-verbose-logging) for the session so that we can investigate further.

**Comment by Eanam** [comment]
This is the logs we catch, 'xxx' is package name which is not important.

> 2023-07-13 16:59:37.984 22216-22504 AppLovinSdk             xxx              D  [TaskCacheNativeAd] Attempting to cache resource: https://images.startappservice.com/image/fetch/f_auto,q_auto,e_sharpen,w_1200,h_627/https%3A%2F%2Fs.yimg.com%2Fav%2Fcurveball%2Fads%2Fpr%2FRESIZE_AND_CROP%2F1200x627%2Fc626715f1fce1e3a2b720d66accc4b42.jpeg
2023-07-13 16:59:37.985 22216-22504 AppLovinSdk             xxx              D  [FileManager] Looking up cached resource: b2fbe99e-360e-49ad-ab6c-4ad731c2bcc2image_fetch_f_auto,q_auto,e_sharpen,w_1200,h_627_https://s.yimg.com/av/curveball/ads/pr/RESIZE_AND_CROP/1200x627/c626715f1fce1e3a2b720d66accc4b42.jpeg
2023-07-13 16:59:37.986 22216-22504 AppLovinSdk             xxx              D  [FileManager] Loading https://images.startappservice.com/image/fetch/f_auto,q_auto,e_sharpen,w_1200,h_627/https%3A%2F%2Fs.yimg.com%2Fav%2Fcurveball%2Fads%2Fpr%2FRESIZE_AND_CROP%2F1200x627%2Fc626715f1fce1e3a2b720d66accc4b42.jpeg...
2023-07-13 16:59:38.015 22216-22504 AppLovinSdk             xxx              D  [FileManager] Opened stream to resource https://images.startappservice.com/image/fetch/f_auto,q_auto,e_sharpen,w_1200,h_627/https%3A%2F%2Fs.yimg.com%2Fav%2Fcurveball%2Fads%2Fpr%2FRESIZE_AND_CROP%2F1200x627%2Fc626715f1fce1e3a2b720d66accc4b42.jpeg
2023-07-13 16:59:38.015 22216-22504 AppLovinSdk             xxx              D  [FileManager] Caching /data/user/0/xxx/files/al/b2fbe99e-360e-49ad-ab6c-4ad731c2bcc2image_fetch_f_auto,q_auto,e_sharpen,w_1200,h_627_https:/s.yimg.com/av/curveball/ads/pr/RESIZE_AND_CROP/1200x627/c626715f1fce1e3a2b720d66accc4b42.jpeg...
2023-07-13 16:59:38.016 22216-22504 AppLovinSdk             xxx              D  [FileManager] Writing resource to filesystem: c626715f1fce1e3a2b720d66accc4b42.jpeg
2023-07-13 16:59:38.017 22216-22504 AppLovinSdk             xxx              E  [FileManager] Unknown failure to write file.
                                                                                                    java.io.FileNotFoundException: /data/user/0/xxx/files/al/b2fbe99e-360e-49ad-ab6c-4ad731c2bcc2image_fetch_f_auto,q_auto,e_sharpen,w_1200,h_627_https:/s.yimg.com/av/curveball/ads/pr/RESIZE_AND_CROP/1200x627/c626715f1fce1e3a2b720d66accc4b42.jpeg: open failed: ENOENT (No such file or directory)
                                                                                                    at libcore.io.IoBridge.open(IoBridge.java:574)
                                                                                                    at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
                                                                                                    at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
                                                                                                    at com.applovin.impl.sdk.r.a(Unknown Source:43)
                                                                                                    at com.applovin.impl.sdk.r.b(Unknown Source:46)
                                                                                                    at com.applovin.impl.sdk.r.a(Unknown Source:62)
                                                                                                    at com.applovin.impl.sdk.r.a(Unknown Source:97)
                                                                                                    at com.applovin.impl.sdk.r.a(Unknown Source:8)
                                                                                                    at com.applovin.impl.sdk.nativeAd.a.a(Unknown Source:105)
                                                                                                    at com.applovin.impl.sdk.nativeAd.a.run(Unknown Source:69)
                                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                                    at libcore.io.Linux.open(Native Method)
                                                                                                    at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
                                                                                                    at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7784)
                                                                                                    at libcore.io.IoBridge.open(IoBridge.java:560)
                                                                                                    at java.io.FileOutputStream.<init>(FileOutputStream.java:236) 
                                                                                                    at java.io.FileOutputStream.<init>(FileOutputStream.java:186) 
                                                                                                    at com.applovin.impl.sdk.r.a(Unknown Source:43) 
                                                                                                    at com.applovin.impl.sdk.r.b(Unknown Source:46) 
                                                                                                    at com.applovin.impl.sdk.r.a(Unknown Source:62) 
                                                                                                    at com.applovin.impl.sdk.r.a(Unknown Source:97) 
                                                                                                    at com.applovin.impl.sdk.r.a(Unknown Source:8) 
                                                                                                    at com.applovin.impl.sdk.nativeAd.a.a(Unknown Source:105) 
                                                                                                    at com.applovin.impl.sdk.nativeAd.a.run(Unknown Source:69) 
                                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463) 
                                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
                                                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307) 
                                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    at java.lang.Thread.run(Thread.java:1012)
