### ISSUE TITLE
No stable max and pangle version combinations found

### ISSUE THREAD

**Issue by JasonDisel** [AppLovin/AppLovin-MAX-SDK-Android#219]
Can you provide a more stable combination of the max version and the pangle version? At present, I have tried many combinations and reported crashes.
Our 10 million daily active app project cannot be integrated, please solve it as soon as possible，thank you
for example：
   1、max 11.2.0,pangle-adapter:4.2.5.2.5
   Open the obfuscated release package, and it will crash on startup，Details are as follows：
  022-03-03 18:25:49.544 28907-28907/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: （packageName）, PID: 28907
    java.lang.RuntimeException: Unable to instantiate application （packageName）.App: java.lang.NullPointerException: throw with null exception
        at android.app.LoadedApk.makeApplication(LoadedApk.java:579)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4658)
        at android.app.ActivityThread.access$1600(ActivityThread.java:164)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1438)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5408)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
     Caused by: java.lang.NullPointerException: throw with null exception
        at sj.a.<init>(ActivationDataReader.java)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1606)
        at o60.a.a(AppJoint.java:28)
        at wm.a.b(ILaunchTime.kt:4)
        at wm.b.d(ILaunchTime.kt:72)
        at wm.d.a(LaunchTimeProxy.kt:253)
        at fn.a$a.a(ILaunchTimeProxy.kt)
        at （packageName）.App.attachBaseContext(App.java:130)
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:996)
        at android.app.Instrumentation.newApplication(Instrumentation.java:980)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:574)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4658) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1438) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5408) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
   
   2、max：11.1.0。   pangle-adapter： 4.0.1.4.0
      Crashes when you get the pangle ad，Details are as follows：

     AndroidRuntime: FATAL EXCEPTION: main
Process: （packageName）, PID: 19089
java.lang.NoSuchMethodError: No direct method <init>(Lcom/applovin/mediation/nativeAds/MaxNativeAd;Ljava/lang/String;Landroid/app/Activity;)V in class Lcom/applovin/mediation/nativeAds/MaxNativeAdView; or its super classes (declaration of 'com.applovin.mediation.nativeAds.MaxNativeAdView' appears in /data/app/~~v2pNejshVnSi8ZSjq8UD-w==/（packageName）-Am0hymWQy0FI22dzUk9NUA==/base.apk!classes2.dex)
at com.applovin.mediation.adapters.ByteDanceMediationAdapter$NativeAdListener$1$1.run(ByteDanceMediationAdapter.java:125)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:8063)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:676)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by thomasmso** [comment]
Hi - this might be related to Pangle native banners - what version are you on? v4.1.1.9.2 has a fix for it.

**Comment by JasonDisel** [comment]
> 嗨 - 这可能与 Pangle 原生横幅有关 - 你使用的是什么版本？v4.1.1.9.2 对此进行了修复。

But I used it in my self-test, max 11.2.0, pangle-adapter: 4.2.5.2.5, there is still a problem, the crash log is as above

**Comment by thomasmso** [comment]
@JasonDisel - Can you send me your APK? thomas.so@applovin.com
