### ISSUE TITLE
Fatal Exception: android.util.AndroidRuntimeException

### ISSUE THREAD

**Issue by hoanghiephui** [AppLovin/AppLovin-MAX-SDK-Android#221]
SDK: 11.2.1

Fatal Exception: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:435)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
       at android.webkit.WebView.getFactory(WebView.java:2576)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2570)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2638)
       at android.view.View.<init>(View.java:5341)
       at android.view.View.<init>(View.java:5487)
       at android.view.ViewGroup.<init>(ViewGroup.java:701)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
       at android.webkit.WebView.<init>(WebView.java:413)
       at android.webkit.WebView.<init>(WebView.java:355)
       at android.webkit.WebView.<init>(WebView.java:337)
       at android.webkit.WebView.<init>(WebView.java:324)
       at android.webkit.WebView.<init>(WebView.java:314)
       at com.applovin.impl.sdk.k$2.run(k.java:12)
       at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(AppLovinSdkUtils.java:8)
       at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(AppLovinSdkUtils.java:1)
       at com.applovin.impl.sdk.k.c(k.java:25)
       at com.applovin.impl.sdk.UserServiceImpl.preloadConsentDialog(UserServiceImpl.java:6)

**Comment by chauduyphanvu** [comment]
@hoanghiephui, do you know how often this is happening? 

From the stack trace it seems to only happen when we try to create a WebView for ads and it's not available on the device (either it's getting updated by the Android OS or the users don't have it on their phones, which is very rare).

Either way let me see if we can mitigate this from the SDK.

Vu Chau
AppLovin Team

**Comment by hoanghiephui** [comment]
> @hoanghiephui, do you know how often this is happening?
> 
> From the stack trace it seems to only happen when we try to create a WebView for ads and it's not available on the device (either it's getting updated by the Android OS or the users don't have it on their phones, which is very rare).
> 
> Either way let me see if we can mitigate this from the SDK.
> 
> Vu Chau AppLovin Team

Hi Vu,
It happens when I try to call the method **preloadConsentDialog**

**Comment by chauduyphanvu** [comment]
@hoanghiephui - thanks, it will be fixed in the next SDK release!
