### ISSUE TITLE
onNativeAdLoaded callback with a null MaxNativeAdView instance

### ISSUE THREAD

**Issue by glzlaohuai** [AppLovin/AppLovin-MAX-SDK-Android#232]
I build a custom ad adapter, create a native manual ad unit, and test it using the demo app's  mediation debugger.  After I got the native ad load succeeded callback, the loaded ad didn't show up. 

The relevant logs:
```
2022-03-09 11:31:01.309 528-528/com.benqu.wuta D/AppLovinSdk: [CommunicatorService] Sending "max_ad_events" message: Bundle[{network_placement=kPyxJwAj, third_party_ad_placement_id=kPyxJwAj, network_name=CUSTOM_NETWORK_SDK, id=f6ee457c280c439a9fc2374ca075aae98da88d26, type=DID_LOAD, ad_format=NATIVE, max_ad_unit_id=dce1103c1fbc4cf5}]
2022-03-09 11:31:01.310 528-528/com.benqu.wuta D/AppLovinSdk: [TaskProcessMediationWaterfall:dce1103c1fbc4cf5:NATIVE] Ad loaded in 16ms
2022-03-09 11:31:01.311 528-528/com.benqu.wuta D/AppLovinSdk: [MediationWaterfallWinnerTracker] Tracking winning ad: MediatedAd{thirdPartyAdPlacementId=kPyxJwAj, adUnitId=dce1103c1fbc4cf5, format=NATIVE, networkName='APSDK_Test'}
2022-03-09 11:31:01.311 528-528/com.benqu.wuta I/AppLovinSdk: [TaskProcessMediationWaterfall:dce1103c1fbc4cf5:NATIVE] Waterfall loaded in 17ms for CUSTOM_NETWORK_SDK
2022-03-09 11:31:01.311 528-1110/com.benqu.wuta I/AppLovinSdk: [ConnectionManager] Sending GET request to id=#-1380153749 "prod-ms.applovin.com/1.0/event/load"...
2022-03-09 11:31:01.311 528-528/com.benqu.wuta D/AppLovinSdk: [MaxNativeAdLoader] No native ad view to render. Returning the native ad to be rendered later.
2022-03-09 11:31:01.314 528-528/com.benqu.wuta E/AppLovinSdk: [ListenerCallbackInvoker] Unable to notify ad event listener about native ad being loaded
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.setLayoutParams(android.view.ViewGroup$LayoutParams)' on a null object reference
        at com.applovin.impl.mediation.debugger.ui.a.d.onCreate(Unknown Source:39)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:424)
        at android.app.Dialog.show(Dialog.java:318)
        at com.applovin.impl.mediation.debugger.ui.a.a.a(Unknown Source:27)
        at com.applovin.impl.mediation.debugger.ui.a.a.onAdLoaded(Unknown Source:76)
        at com.applovin.impl.mediation.debugger.ui.a.a$2.onNativeAdLoaded(Unknown Source:7)
        at com.applovin.impl.sdk.utils.j$20.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by maxakash** [comment]
You have to pass an instance of MaxNativeAdView while calling load()

**Comment by glzlaohuai** [comment]
It seems like the `Max Mediation Debugger` is a part of the SDK, so I think there is no way I can change the `load` method.

**Comment by maxakash** [comment]
> It seems like the `Max Mediation Debugger` is a part of the SDK, so I think there is no way I can change the `load` method.

I meant `nativeAdLoader.loadAd( createNativeAdView() ) `

**Comment by glzlaohuai** [comment]
Yes, I know that I can make a simple demo by myself, but I just want to do a quick test by just invoking SDK's initialize method. And it's convenient to use the built-in test mode function to test my custom network adapter. So it would be nice to have this issue be fixed
