### ISSUE TITLE
Cannot update security provider     com.google.android.gms.common.GooglePlayServicesNotAvailableException

### ISSUE THREAD

**Issue by xiaopei** [AppLovin/AppLovin-MAX-SDK-Android#254]
I saw below logs in my logcat ,what does this mean?

E/AppLovinSdk: [TaskFetchBasicSettings] Cannot update security provider
    com.google.android.gms.common.GooglePlayServicesNotAvailableException
        at com.google.android.gms.common.GooglePlayServicesUtilLight.ensurePlayServicesAvailable(com.google.android.gms:play-services-basement@@18.0.0:5)
        at com.google.android.gms.common.GoogleApiAvailabilityLight.verifyGooglePlayServicesIsAvailable(com.google.android.gms:play-services-basement@@18.0.0:1)
        at com.google.android.gms.security.ProviderInstaller.installIfNeeded(com.google.android.gms:play-services-basement@@18.0.0:2)
        at com.applovin.impl.sdk.e.h.run(Unknown Source:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)

**Comment by chauduyphanvu** [comment]
@xiaopei - thanks for the report. This looks like we are running this check (https://developer.android.com/training/articles/security-gms-provider#example_sync) and your device doesn't have Google Play services installed. Since the exception is caught, this should not be serious. You can ignore it.
