### ISSUE TITLE
[ANR] com.applovin.mediation.adapters.GoogleMediationAdapter.loadAdViewAd

### ISSUE THREAD

**Issue by raghav2945** [AppLovin/AppLovin-MAX-SDK-Android#261]
### Describe the bug
We ([Audiomack](https://audiomack.com/)) start observing a new issue in our latest release. It's a from the Applovin component. This is primarily related to Google Ads' loadAdViewAd. Despite the fact that the count is currently low, it has been highlighted in our analytical tools as one of the top five. The count is less because the latest version adoption is slow and low. Sharing the stacktrace for your reference. And this issue is primarily observed on Android 11. 

Please find Applovin SDK and other related component version information below.:

```
    // AppLovin-MAX
    implementation 'com.applovin:applovin-sdk:11.3.0'

    // Google Ad Manager 
    implementation 'com.google.android.gms:play-services-ads:20.6.0'

    // Admob through AppLovin-MAX
    implementation 'com.applovin.mediation:google-adapter:20.6.0.3'
```

### Stack-trace

```
main (runnable): tid=1 systid=30949
       at com.google.android.gms.common.GoogleApiAvailabilityLight.getInstance(GoogleApiAvailabilityLight.java)
       at com.google.android.gms.internal.ads.zzcis.zzn(zzcis.java:1)
       at com.google.android.gms.internal.ads.zzbgn.zzd(zzbgn.java:2)
       at com.google.android.gms.internal.ads.zzbgm.zzc(zzbgm.java:2)
       at com.google.android.gms.ads.AdLoader$Builder.<init>(AdLoader.java:3)
       at com.applovin.mediation.adapters.GoogleMediationAdapter.loadAdViewAd(GoogleMediationAdapter.java:490)
       at com.applovin.impl.mediation.g$13.run(g.java)
       at com.applovin.impl.mediation.g$14.run(g.java)
       at com.applovin.impl.mediation.g$8.run(g.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by Lorenzo45** [comment]
Do you have a contact at AdMob that you can forward this ANR to? It looks like this ANR is coming from their SDK and Google requires that we call these methods on the main thread so it appears to be out of our hands.

If you have a Crashlytics report for this ANR it should have more information which would be useful for debugging.

Is this ANR new? If so, what changes were made just before it was introduced?

**Comment by raghav2945** [comment]
Yes, it is a new issue, and we believe it was caused by the shift from AdMobs to Maxx. 
And I'll get back to you as soon as possible on the rest of your questions.

**Comment by raghav2945** [comment]
I'm not very sure which log you want us to share; I'm sharing the log file I received for this ANR over Firebase. 

Aside from that, please let us know how we can assist you with this issue, as this is not locally reproducible, making it difficult to obtain specific logs. For any type of input, we are completely reliant on Firebase.

**Comment by raghav2945** [comment]
Not only through admobs, but also through Mintegral and Chartboost this issue has been observed. If you make it clear that we need to contact each unit separately, or can we expect a concrete solution from Applovin?

**Comment by Lorenzo45** [comment]
You should send the main thread stack trace above to Google with the full context. Specifically this part of the stack trace is coming from their SDK:
```
       at com.google.android.gms.common.GoogleApiAvailabilityLight.getInstance(GoogleApiAvailabilityLight.java)
       at com.google.android.gms.internal.ads.zzcis.zzn(zzcis.java:1)
       at com.google.android.gms.internal.ads.zzbgn.zzd(zzbgn.java:2)
       at com.google.android.gms.internal.ads.zzbgm.zzc(zzbgm.java:2)
       at com.google.android.gms.ads.AdLoader$Builder.<init>(AdLoader.java:3)
```

Do the Mintegral and Chartboost ANRs have the same stack trace?

**Comment by raghav2945** [comment]
The one I mentioned earlier is the maximum log or stack that we received from Firebase on the main thread. 

The other two stacks are as follows:

### Chartboost

```
main (runnable): tid=1 systid=24038
       at android.os.BaseBundle.getString(BaseBundle.java:1196)
       at com.applovin.mediation.adapters.ChartboostMediationAdapter.initialize(ChartboostMediationAdapter.java:94)
       at com.applovin.impl.mediation.g$1.run(g.java)
       at com.applovin.impl.mediation.g$8.run(g.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
### Mintegral

```
main (runnable): tid=1 systid=1976
       at com.applovin.mediation.adapters.MintegralMediationAdapter.initialize(MintegralMediationAdapter.java:137)
       at com.applovin.impl.mediation.g$1.run(g.java)
       at com.applovin.impl.mediation.g$8.run(g.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7703)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

```

In addition, we are observing ANR from the start of chartboost. According to Firebase, one stack represents the root blocking and the other represents the triggered ANR. Sharing both the stack as below

> **Root Blocking**

```
Chartboost Thread #1 (timed waiting): tid=191 systid=6812
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
       at com.google.android.gms.common.BlockingServiceConnection.getServiceWithTimeout(BlockingServiceConnection.java:3)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zzb(AdvertisingIdClient.java:14)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(AdvertisingIdClient.java:3)
       at com.chartboost.sdk.impl.l.a(l.java:2)
       at com.chartboost.sdk.impl.k.<init>(k.java:4)
       at com.chartboost.sdk.impl.m0.b(m0.java:1)
       at com.chartboost.sdk.impl.m0.c(m0.java:6)
       at com.chartboost.sdk.impl.l2.e(l2.java:1)
       at com.chartboost.sdk.impl.m1.a(m1.java:30)
       at com.chartboost.sdk.impl.m1.b(m1.java:27)
       at com.chartboost.sdk.impl.m1.$r8$lambda$kk-k4qqqyTvTXf7WxwQkb1ct3w0(m1.java)
       at com.chartboost.sdk.impl.m1$$ExternalSyntheticLambda0.run(m1.java)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

> **Triggered ANR**

```
main (blocked): tid=1 systid=5229
       at com.chartboost.sdk.impl.m0.d(m0.java)
       at com.chartboost.sdk.f$b.run(f.java:58)
       at com.chartboost.sdk.f.d(f.java:1)
       at com.chartboost.sdk.f.b(f.java:4)
       at com.chartboost.sdk.f.a(f.java:12)
       at com.chartboost.sdk.f$a.a(f.java:7)
       at com.chartboost.sdk.impl.s0.a(s0.java:93)
       at com.chartboost.sdk.Networking.c.run(c.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7703)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

**Comment by raghav2945** [comment]
@Lorenzo45 , We must express our deep concern about the most recent Chartboost issue, and we are looking for immediate assistance. It has recorded **2725 ANR events in the last two days, affecting 1919 users**. This is the most we have now for any issue. It is a new issue that has contributed to a sudden increase in the ANR count in our application. I see that we upgraded SDK related to chartboost to "com.applovin.mediation-chartboost-adapter-8.4.0.0," which is the only difference between the previous and current releases.

**Comment by Lorenzo45** [comment]
Have you tried downgrading the Chartboost SDK? That would be my first recommendation.

In the meantime, you should reach out directly to Chartboost about this issue as we cannot fix it for them. If you don't have a contact at Chartboost we may be able to help get you one.

**Comment by raghav2945** [comment]
> Have you tried downgrading the Chartboost SDK? That would be my first recommendation.
> 
> In the meantime, you should reach out directly to Chartboost about this issue as we cannot fix it for them. If you don't have a contact at Chartboost we may be able to help get you one.

@Lorenzo45 thank you!
Yes, that is our first line of defense to downgrade before we receive anything from Chartboost. I am unable to contact our SDK management team; in the meantime, I would appreciate it if you could share the point of contact for them. If we don't have anyone, it will help us speed up the process.

Aside from this 3rd party SDK issue, we've been receiving some core Applovin ANR issues, and we've shared here the stack-trace for your convenience. If you could take a look and advise us on how to avoid such a problem, that would be greatly appreciated.

```
main (native): tid=1 systid=23778 
#00 pc 0xa0078 libc.so 
#01 pc 0x6c2f3 libc.so 
#02 pc 0x3a2c7 libbinder.so 
#03 pc 0x3b215 libbinder.so 
#04 pc 0x3afdb libbinder.so 
#05 pc 0x356bf libbinder.so 
#06 pc 0xce143 libandroid_runtime.so 
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:605)
       at android.app.IActivityManager$Stub$Proxy.getMyMemoryState(IActivityManager.java:9045)
       at android.app.ActivityManager.getMyMemoryState(ActivityManager.java:4414)
       at com.iab.omid.library.applovin.b.b.d(b.java)
       at com.iab.omid.library.applovin.b.b.onActivityStopped(b.java)
       at android.app.Application.dispatchActivityStopped(Application.java:515)
       at android.app.Activity.dispatchActivityStopped(Activity.java:1479)
       at android.app.Activity.onStop(Activity.java:2643)
       at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:496)
       at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:252)
       at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1476)
       at android.app.Activity.performStop(Activity.java:8429)
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5367)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5310)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5420)
       at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2315)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8550)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by thomasmso** [comment]
@raghav2945 - How often is the ANR above occurring?

**Comment by raghav2945** [comment]
> @raghav2945 - How often is the ANR above occurring?

@thomasmso, Currently, the count is very low, with only about 100 instances reported over Firebase in the last 7 day. However, it is marked as fresh, so I'd like to bring it to yours team attention if something similar has been reported previously and we're missing something while integrating MAX in our codebase.

**Comment by thomasmso** [comment]
Thanks @raghav2945 - we'll raise it with the OMID team.

**Comment by raghav2945** [comment]
> > Have you tried downgrading the Chartboost SDK? That would be my first recommendation.
> > In the meantime, you should reach out directly to Chartboost about this issue as we cannot fix it for them. If you don't have a contact at Chartboost we may be able to help get you one.
> 
> @Lorenzo45 thank you! Yes, that is our first line of defense to downgrade before we receive anything from Chartboost. I am unable to contact our SDK management team; in the meantime, I would appreciate it if you could share the point of contact for them. If we don't have anyone, it will help us speed up the process.
> 
> Aside from this 3rd party SDK issue, we've been receiving some core Applovin ANR issues, and we've shared here the stack-trace for your convenience. If you could take a look and advise us on how to avoid such a problem, that would be greatly appreciated.
> 
> ```
> main (native): tid=1 systid=23778 
> #00 pc 0xa0078 libc.so 
> #01 pc 0x6c2f3 libc.so 
> #02 pc 0x3a2c7 libbinder.so 
> #03 pc 0x3b215 libbinder.so 
> #04 pc 0x3afdb libbinder.so 
> #05 pc 0x356bf libbinder.so 
> #06 pc 0xce143 libandroid_runtime.so 
>        at android.os.BinderProxy.transactNative(BinderProxy.java)
>        at android.os.BinderProxy.transact(BinderProxy.java:605)
>        at android.app.IActivityManager$Stub$Proxy.getMyMemoryState(IActivityManager.java:9045)
>        at android.app.ActivityManager.getMyMemoryState(ActivityManager.java:4414)
>        at com.iab.omid.library.applovin.b.b.d(b.java)
>        at com.iab.omid.library.applovin.b.b.onActivityStopped(b.java)
>        at android.app.Application.dispatchActivityStopped(Application.java:515)
>        at android.app.Activity.dispatchActivityStopped(Activity.java:1479)
>        at android.app.Activity.onStop(Activity.java:2643)
>        at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:496)
>        at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:252)
>        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1476)
>        at android.app.Activity.performStop(Activity.java:8429)
>        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5367)
>        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5310)
>        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5420)
>        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40)
>        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
>        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2315)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loop(Looper.java:246)
>        at android.app.ActivityThread.main(ActivityThread.java:8550)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
> ```

Thank you @Lorenzo45 for introducing with the Chartboost team

**Comment by Lorenzo45** [comment]
I don't have a contact for you yet but hopefully we can get you one soon :)

**Comment by thomasmso** [comment]
@raghav2945 - Re: the latest ANR you posted, it's been raised in https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/261 already, and we're working with the vendor on it. A fix would likely require an SDK update on your end though.

**Comment by raghav2945** [comment]
> @raghav2945 - Re: the latest ANR you posted, it's been raised in #261 already, and we're working with the vendor on it. A fix would likely require an SDK update on your end though.

Thank you for providing an update. I'm looking forward to the new SDK update.

**Comment by thomasmso** [comment]
Resolved offline.
