### ISSUE TITLE
MaxAdapterParametersImpl.java ANR

### ISSUE THREAD

**Issue by hoanghiephui** [AppLovin/AppLovin-MAX-SDK-Android#267]
main (runnable): tid=1 systid=23430
       at com.applovin.impl.mediation.MaxAdapterParametersImpl.getServerParameters(MaxAdapterParametersImpl.java)
       at com.applovin.mediation.adapters.ByteDanceMediationAdapter.initialize(ByteDanceMediationAdapter.java:154)
       at com.applovin.impl.mediation.g$1.run(g.java)
       at com.applovin.impl.mediation.g$8.run(g.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7701)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

**Comment by chauduyphanvu** [comment]
@hoanghiephui - could you share the log messages prior to that stack trace? Also, which SDK and/or adapter versions are you using? Thanks.
