### ISSUE TITLE
android.content.Context.getContentResolver()' on a null object reference

### ISSUE THREAD

**Issue by nihp** [AppLovin/AppLovin-MAX-SDK-Android#284]
I an getting android.content.Context.getContentResolver()' on a null object reference error for the first showAd. After rerunnning the app it works s expextd in interstitial ads

It crashes initially on android version 8.1.0

**Comment by santoshbagadi** [comment]
Hi @nihp , could you please share the full stacktrace and verbose logs when the issue is happening.

**Comment by nihp** [comment]
Log from my app on the line ad.showAd() method.


```
AndroidRuntime: FATAL EXCEPTION: main
    Process:  PID: 15033
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4, result=0, data=null} to activity {bundleid/com.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4335)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4379)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
        at android.content.ContextWrapper.getContentResolver(ContextWrapper.java:99)
        at com.applovin.impl.sdk.utils.Utils.getAlwaysFinishActivitiesSetting(Unknown Source:3)
        at com.applovin.impl.mediation.ads.MaxFullscreenAdImpl.a(Unknown Source:63)
        at com.applovin.impl.mediation.ads.MaxFullscreenAdImpl.showAd(Unknown Source:9)
        at com.applovin.mediation.ads.MaxInterstitialAd.showAd(Unknown Source:52)
        at com.applovin.mediation.ads.MaxInterstitialAd.showAd(Unknown Source:1)
        at com.applovin.mediation.ads.MaxInterstitialAd.showAd(Unknown Source:1)
  at com.nAdapter.showAd(Adapter.java:93)
        at InterstitialManager.showAd(InterstitialManager.java:207)
        at MainActivity.showPageAd(MainActivity.java:707)
        at MainActivity.onActivityResult(MainActivity.java:803)
        at android.app.Activity.dispatchActivityResult(Activity.java:7355)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4331)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4379) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6651) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
V/FA: Activity paused, time: 17712856
```

**Comment by santoshbagadi** [comment]
@nihp what version of our SDK are you using? Are you showing the ad in a new activity (which should be fine, but just wanted to double check).

Could you also share full verbose logs when the issue is happening?

**Comment by nihp** [comment]
I have fixed the issue. Thanks for your help.
