### ISSUE TITLE
a crash on com.applovin.impl.sdk.p.a

### ISSUE THREAD

**Issue by xiaopei** [AppLovin/AppLovin-MAX-SDK-Android#292]
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
	at android.os.Parcel.createException(Parcel.java:2093)
	at android.os.Parcel.readException(Parcel.java:2055)
	at android.os.Parcel.readException(Parcel.java:2003)
	at android.app.IActivityManager$Stub$Proxy.getMemoryInfo(IActivityManager.java:6439)
	at android.app.ActivityManager.getMemoryInfo(ActivityManager.java:2433)
	at com.applovin.impl.sdk.p.a(Unknown Source:592)
                            a
                            a
                            a
                            a
                            a
                            a
                            a
                            a
                            a
	at com.applovin.impl.sdk.p.a(Unknown Source:11)
                            a
                            a
                            a
                            a
                            a
                            a
                            a
                            a
                            a
	at com.applovin.impl.sdk.p.a(Unknown Source:7)
                            a
                            a
                            a
                            a
                            a
                            a
                            a
                            a
                            a
	at com.applovin.impl.sdk.EventServiceImpl.a(Unknown Source:24)
                                           a
                                           a
                                           a
                                           a
                                           a
	at com.applovin.impl.sdk.EventServiceImpl.a(Unknown Source:0)
                                           a
                                           a
                                           a
                                           a
                                           a
	at com.applovin.impl.sdk.EventServiceImpl$1.run(Unknown Source:29)
	at com.applovin.impl.sdk.e.z.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by joeapplovin** [comment]
Hello - what is the SDK version you're currently using?

**Comment by xiaopei** [comment]
max-11.3.1

**Comment by joeapplovin** [comment]
Thanks @xiaopei - we'll investigate.  Do you have more information about the crash, such as frequency, repro steps, etc?

**Comment by xiaopei** [comment]
it crash 14 times since 3.4. I got this on our bug system on line, and can not repro yet until now

**Comment by thomasmso** [comment]
@xiaopei - We just released SDK v11.4.3 which fixes this crash. Thanks again for reporting it.
