### ISSUE TITLE
RejectedExecutionException: 

### ISSUE THREAD

**Issue by xiaopei** [AppLovin/AppLovin-MAX-SDK-Android#315]
java.util.concurrent.RejectedExecutionException: Task com.applovin.impl.sdk.e.g@52085e4 rejected from java.util.concurrent.ThreadPoolExecutor@9fcaa4d[Running; pool size = 9; active threads = 9; queued tasks = 128; completed tasks = 59]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2049)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:814)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
	at com.applovin.impl.sdk.e.o.a(Unknown Source)
                              a
                              a
                              a
                              a
                              a
                              a
                              a
                              a
                              a
	at com.applovin.impl.sdk.e.o.a(Unknown Source)
                              a
                              a
                              a
                              a
                              a
                              a
                              a
                              a
                              a
	at com.applovin.impl.sdk.e.o.a(Unknown Source)
                              a
                              a
                              a
                              a
                              a
                              a
                              a
                              a
                              a
	at com.applovin.impl.sdk.e.o.a(Unknown Source)
                              a
                              a
                              a
                              a
                              a
                              a
                              a
                              a
                              a
	at com.applovin.impl.sdk.network.PostbackServiceImpl.dispatchPostbackRequest(Unknown Source)
                                                      dispatchPostbackRequest
	at com.applovin.impl.sdk.network.PostbackServiceImpl.dispatchPostbackRequest(Unknown Source)
                                                      dispatchPostbackRequest
	at com.applovin.impl.sdk.network.f.a(Unknown Source)
                                    a
                                    a
                                    a
                                    a
                                    a
                                    a
                                    a
	at com.applovin.impl.sdk.network.f.a(Unknown Source)
                                    a
                                    a
                                    a
                                    a
                                    a
                                    a
                                    a
	at com.applovin.impl.sdk.network.f$1.run(Unknown Source)
	at com.applovin.impl.sdk.network.f.a(Unknown Source)
                                    a
                                    a
                                    a
                                    a
                                    a
                                    a
                                    a
	at com.applovin.impl.sdk.network.f.a(Unknown Source)
                                    a
                                    a
                                    a
                                    a
                                    a
                                    a
                                    a
	at com.applovin.impl.sdk.network.f.a(Unknown Source)
                                    a
                                    a
                                    a
                                    a
                                    a
                                    a
                                    a
	at com.applovin.impl.sdk.EventServiceImpl$1.run(Unknown Source)
	at com.applovin.impl.sdk.e.z.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**Comment by thomasmso** [comment]
Hi - we're aware of the crash, and will investigate. When we have findings, I'll update this thread.
