### ISSUE TITLE
java.lang.IllegalArgumentException: Error unparceling MemoryIntArray

### ISSUE THREAD

**Issue by xiaopei** [AppLovin/AppLovin-MAX-SDK-Android#317]
java.lang.IllegalArgumentException: Error unparceling MemoryIntArray
	at android.util.MemoryIntArray$1.createFromParcel(MemoryIntArray.java:248)
	at android.util.MemoryIntArray$1.createFromParcel(MemoryIntArray.java:243)
	at android.os.Parcel.readParcelable(Parcel.java:2860)
	at android.os.Parcel.readValue(Parcel.java:2754)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3123)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
	at android.os.BaseBundle.unparcel(BaseBundle.java:226)
	at android.os.BaseBundle.getString(BaseBundle.java:1118)
	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:1946)
	at android.provider.Settings$System.getStringForUser(Settings.java:2325)
	at android.provider.Settings$System.getIntForUser(Settings.java:2440)
	at android.provider.Settings$System.getInt(Settings.java:2434)
	at com.applovin.impl.sdk.p.a(Unknown Source:342)
                            a
                            a
                            a
                            a
                            a
                            a
                            a
                            a
                            a
	at com.applovin.impl.sdk.p.a(Unknown Source:11)
                            a
                            a
                            a
                            a
                            a
                            a
                            a
                            a
                            a
	at com.applovin.impl.sdk.p.d(Unknown Source:1)
	at com.applovin.impl.sdk.e.b.b(Unknown Source:6)
	at com.applovin.impl.sdk.e.b.run(Unknown Source:16)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)

**Comment by thomasmso** [comment]
Thanks for reporting the issue. We'll fix in the next SDK release.

**Comment by thomasmso** [comment]
@xiaopei - How often is this crash occurring, and is it isolated to specific device models or OS versions?

**Comment by thomasmso** [comment]
@xiaopei - This has been fixed in v11.4.0 of our SDK.
