### ISSUE TITLE
App crash(Mintegral native ad)

### ISSUE THREAD

**Issue by silane-tech** [AppLovin/AppLovin-MAX-SDK-Android#336]
App crashes while loading Mintegral native ad.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxxxx.yyyy, PID: 8989
    java.lang.IllegalStateException: Calling View methods on another thread than the UI thread.
        at com.android.webview.chromium.WebViewChromium.b(chromium-Monochrome.aab-stable-451515923:2)
        at com.android.webview.chromium.WebViewChromium.init(chromium-Monochrome.aab-stable-451515923:15)
        at android.webkit.WebView.<init>(WebView.java:678)
        at android.webkit.WebView.<init>(WebView.java:604)
        at android.webkit.WebView.<init>(WebView.java:587)
        at android.webkit.WebView.<init>(WebView.java:574)
        at android.webkit.WebView.<init>(WebView.java:564)
        at com.mbridge.msdk.mbsignalcommon.webEnvCheck.a.a(MBWebViewChecker.java:14)
        at com.mbridge.msdk.mbnative.controller.NativeController.a(NativeController.java:2433)
        at com.mbridge.msdk.mbnative.e.a.a(NativeProvider.java:137)
        at com.mbridge.msdk.mbnative.e.a.a(NativeProvider.java:57)
        at com.mbridge.msdk.out.MBBidNativeHandler.loadMB(MBBidNativeHandler.java:204)
        at com.mbridge.msdk.out.MBBidNativeHandler.bidLoad(MBBidNativeHandler.java:105)
        at com.applovin.mediation.adapters.MintegralMediationAdapter.loadNativeAd(MintegralMediationAdapter.java:606)
        at com.applovin.impl.mediation.g$12.run(Unknown Source:18)
        at com.applovin.impl.mediation.g$14.run(Unknown Source:4)
        at com.applovin.impl.mediation.g$8.run(Unknown Source:56)
        at com.applovin.impl.mediation.g.a(Unknown Source:19)
        at com.applovin.impl.mediation.g.a(Unknown Source:143)
        at com.applovin.impl.mediation.MediationServiceImpl.loadThirdPartyMediatedAd(Unknown Source:109)
        at com.applovin.impl.mediation.b.e$a.run(Unknown Source:128)
        at com.applovin.impl.sdk.e.o.a(Unknown Source:2)
        at com.applovin.impl.mediation.b.e.run(Unknown Source:107)
        at com.applovin.impl.sdk.e.o.a(Unknown Source:2)
        at com.applovin.impl.mediation.b.c.a(Unknown Source:75)
        at com.applovin.impl.mediation.b.c.a(Unknown Source:0)
        at com.applovin.impl.mediation.b.c$1.a(Unknown Source:28)
        at com.applovin.impl.mediation.b.c$1.a(Unknown Source:2)
        at com.applovin.impl.sdk.e.u$1.a(Unknown Source:12)
        at com.applovin.impl.sdk.network.b$b.a(Unknown Source:148)
        at com.applovin.impl.sdk.network.b$b.accept(Unknown Source:2)
        at com.applovin.impl.sdk.network.e$a$1.run(Unknown Source:8)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
`

**Comment by thomasmso** [comment]
Hi, are you in test mode when encountering this issue?

**Comment by silane-tech** [comment]
Yes!

**Comment by thomasmso** [comment]
We'll work on a fix and get back to you, thank you for reporting it

**Comment by maximilianbuck** [comment]
@silane-tech We've deployed a backend fix for this issue.

**Comment by silane-tech** [comment]
@maximilianbuck But still mintegral native ad does not work.

`E/AppLovinSdk: [AppLovinSdk] 
    **************************************************
    NO FILL received:
    ..ID: "test_mode_native"
    ..FORMAT: "NATIVE"
    ..SDK KEY: "h-yyyyyyyyyyy-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    ..PACKAGE NAME: "com.xxxxxxxxx.yyyyyyyyy"
    ..Reason: [{"code":1000,"msg":"Ad network does not match filter ad networks list"}]
    **************************************************`

**Comment by thomasmso** [comment]
@silane-tech - Please enable test ads from the Mediation Debugger or our UI to ensure fill for networks.

**Comment by silane-tech** [comment]
@thomasmso I have tried, still getting same.

**Comment by thomasmso** [comment]
Confirmed. We'll slot it into the queue to fix.

**Comment by Luklek** [comment]
> E/AppLovinSdk: [AppLovinSdk] ************************************************** NO FILL received: ..ID: "test_mode_native" ..FORMAT: "NATIVE" ..SDK KEY: "h-yyyyyyyyyyy-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" ..PACKAGE NAME: "com.xxxxxxxxx.yyyyyyyyy" ..Reason: [{"code":1000,"msg":"Ad network does not match filter ad networks list"}] **************************************************

I am getting the same error in test mode with Pangle and Meta native ads too. But then the published app on Google Play is getting live ads properly, so it's an issue with test mode?

**Comment by silane-tech** [comment]
For me, Meta is working but Mintegral live and test native ads are not.
