### ISSUE TITLE
java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

### ISSUE THREAD

**Issue by vovasazonov** [AppLovin/AppLovin-MAX-SDK-Android#48]
Hi!
I have crash on devices with android version Oreo 8.0.0.
Is applovin use `com.mbridge.msdk.activity.DomainMBCommonActivity` ?

```
Caused by java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
       at android.app.Activity.onCreate(Activity.java:1038)
       at com.mbridge.msdk.activity.DomainMBCommonActivity.onCreate(DomainMBCommonActivity.java:31)
       at android.app.Activity.performCreate(Activity.java:7183)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
       
```
mb-reward-load-thread
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:325)
       at android.os.Looper.loop(Looper.java:142)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

```
Thread-193
       at java.lang.Thread.sleep(Thread.java)
       at java.lang.Thread.sleep(Thread.java:373)
       at java.lang.Thread.sleep(Thread.java:314)
       at com.adcolony.sdk.g0.a(SourceFile:14)
       at com.adcolony.sdk.g0.run(SourceFile:99)
       at java.lang.Thread.run(Thread.java:764)
```

```
AppLovinSdk:shared_thread_pool:Mf57
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2135)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1120)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

I have no idea because it crashes after applovin threads 

I saw that the problem is very popular and it is issue of google for Android Oreo 8.0.0. 
Can you suggest to me what I should do? Can you confirm that there are problems in side of applovin?

**Comment by thomasmso** [comment]
Hi, `com.mbridge.msdk.activity.DomainMBCommonActivity` is from Mintegral's SDK. Please raise the issue with them to fix. Thanks.
