### ISSUE TITLE
Game crashed : "java.lang.NullPointerException"

### ISSUE THREAD

**Issue by MaVuong** [AppLovin/AppLovin-MAX-SDK-Android#52]
I have error with Android 8.0, 11.0 . devices

java.lang.NullPointerException

java.lang.NullPointerException: 	at com.applovin.mediation.adapters.GoogleMediationAdapter$NativeAdViewListener.onNativeAdLoaded(GoogleMediationAdapter.java:983)
	at com.google.android.gms.internal.ads.zzbyp.zze(zzbyp.java:2)
	at com.google.android.gms.internal.ads.zzbnj.zzbT(zzbnj.java:6)
	at com.google.android.gms.internal.ads.zzow.onTransact(zzow.java:3)
	at android.os.Binder.transact(Binder.java:612)
	at zm.bb(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:2)
	at com.google.android.gms.ads.internal.formats.client.ak.e(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:0)
	at com.google.android.gms.ads.nonagon.ad.nativead.ae.run(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:5)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at atv.a(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:0)
	at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:1)
	at atv.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@213806100@213806100000.397311113.397311113:0)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6942)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

**Comment by thomasmso** [comment]
Hi @MaVuong - Thanks for reporting this. We've fixed it in our latest AdMob adapter v20.4.0.1.
