### ISSUE TITLE
requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by lishun001** [AppLovin/AppLovin-MAX-SDK-Android#536]
### MAX SDK Version

11.5.5

### Device/Platform Info

Android6.0.1

### Current Behavior

Caused by android.util.AndroidRuntimeException: requestFeature() must be called before adding content
       at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:403)
       at android.app.Activity.requestWindowFeature(Activity.java:4008)
       at com.inmobi.media.cw.a(InMobiActivityAdViewHandler.java:11)
       at com.inmobi.ads.rendering.InMobiAdActivity.onNewIntent(InMobiAdActivity.java:7)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1241)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1253)
       at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3490)
       at android.app.ActivityThread.performNewIntents(ActivityThread.java:3502)
       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3511)
       at android.app.ActivityThread.access$1900(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1898)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

### How to Reproduce

During an ad

### Additional Info

Available on Android 6.0 and below

**Comment by thomasmso** [comment]
Hi - this crash is coming from InMobi's SDK. Please raise this issue with them and/or update to the latest adapter/SDK if you havn't already.
