### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by lishun001** [AppLovin/AppLovin-MAX-SDK-Android#537]
### MAX SDK Version

11.5.5

### Device/Platform Info

Android13

### Current Behavior

Caused by java.util.ConcurrentModificationException:
       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1453)
       at java.util.HashMap$EntryIterator.next(HashMap.java:1487)
       at java.util.HashMap$EntryIterator.next(HashMap.java:1485)
       at com.unity3d.scar.adapter.v2000.c.c$a.run(SignalsReader.java:2)
       at f.e.a.a.a.a.d(DispatchGroup.java:2)
       at f.e.a.a.a.a.b(DispatchGroup.java:2)
       at com.unity3d.scar.adapter.v2000.c.a.onSuccess(QueryInfoCallback.java:2)
       at com.google.android.gms.internal.ads.zzcci.zzc(com.google.android.gms:play-services-ads-lite@@20.6.0:2)
       at com.google.android.gms.internal.ads.zzchp.zzbQ(com.google.android.gms:play-services-ads-lite@@20.6.0:4)
       at com.google.android.gms.internal.ads.zzaok.onTransact(com.google.android.gms:play-services-ads-base@@20.6.0:3)
       at android.os.Binder.transact(Binder.java:921)
       at agc.ba(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:8)
       at com.google.android.gms.ads.internal.signals.a.f(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:15)
       at com.google.android.gms.ads.nonagon.signalgeneration.v.b(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:384)
       at bry.run(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:30)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at ate.a(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:1)
       at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:2)
       at ate.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@232400001@232400000057.538171701.538171701:1)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

### How to Reproduce

The specifics are unknown, guess may be related to loading ads

**Comment by thomasmso** [comment]
Hi - based off of these two lines:

```
at com.unity3d.scar.adapter.v2000.c.a.onSuccess(QueryInfoCallback.java:2)
at com.google.android.gms.internal.ads.zzcci.zzc(com.google.android.gms:play-services-ads-lite@@20.6.0:2)
```

the issue is with AdMob and Unity SDKs interactions. 

I'd recommend updating to the latest SDKs to see if it resolves the issue.
