### ISSUE TITLE
AppLovinFullscreenThemedActivity in AndroidManifest.xml

### ISSUE THREAD

**Issue by godepGJ** [AppLovin/AppLovin-MAX-SDK-Android#565]
### MAX SDK Version

11.11.3

### Device/Platform Info

Samsung, OnePlus and more

### Current Behavior

i'm getting an error from Crashlytics

Fatal Exception: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.xxx.xxx/com.applovin.adview.AppLovinFullscreenThemedActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2203)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1845)
       at android.app.Activity.startActivityForResult(Activity.java:5507)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
       at android.app.Activity.startActivityForResult(Activity.java:5465)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:761)
       at android.app.Activity.startActivity(Activity.java:5969)
       at android.app.Activity.startActivity(Activity.java:5930)
       at com.applovin.impl.adview.q.a(SourceFile:448)
       at com.applovin.impl.adview.q.a(SourceFile:52)
       at com.applovin.impl.adview.q$2$1.run(SourceFile:297)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7959)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

![image](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/89415694/8fe23822-e45c-4266-a750-054d47a2428f)

![image](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/89415694/f0d299e6-23b8-4163-94bb-9dfdfeb785da)

![image](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/89415694/f46005ec-68fb-4533-ae52-3dd4b16f37e9)

![image](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/89415694/18d58bea-d617-4f82-b46b-1f4ee42b80e3)

![image](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/89415694/aae64201-463c-4b74-972f-ca2d17e1f20d)

### How to Reproduce

App release playstore

**Comment by applovinAsh** [comment]
Hi @godepGJ, 
Can you provide more detail about when this crash happened? Is it happening with all ad types or just a specific one? Have you been able to recreate the issue?

**Comment by godepGJ** [comment]
I'm looking for that.
I only see ad test when I run it in the emulator.
On my phone there is no problem.

I think it happens on certain ads, but how can I get it?

**Comment by godepGJ** [comment]
BTW, what ad calls for AppLovinFullscreenThemedActivity class? Interstitial or Rewarded ads?

**Comment by applovinAsh** [comment]
@godepGJ, you will only receive test ads when using the emulator. AppLovinFullscreenThemedActivity class gets called from interstitial ads. If you are able to recreate the issue, can you provide us with the creative debugger log. To enable the creative debugger, see here: https://dash.applovin.com/documentation/mediation/android/testing-networks/creative-debugger

**Comment by godepGJ** [comment]
2 days I tried interstitial and rewarded ads. but error was not found.
I know about  creative debugger,  how to get ads that can cause errors like in Crashlytics?

**Comment by applovinAsh** [comment]
Does Crashlytics provide any information regarding the location or specific device?

**Comment by godepGJ** [comment]
Last 24 hour
- Google  Pixel 2 XL (Android 11)
- Xiaomi Poco F4 (Android 13)
- Xiaomi Poco X3 Pro (Android 13)
- Samsung Galaxy S20 Ultra 5G (Android 7.1.2)
- OnePlus 7 Pro (Android 10)
- Realme Monet (Android 12)

Orientation : Portrait
Country/Location : No data

Stack Trace Applovin:
```
Fatal Exception: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.my.app/com.applovin.adview.AppLovinFullscreenThemedActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2164)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1807)
       at android.app.Activity.startActivityForResult(Activity.java:5574)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
       at android.app.Activity.startActivityForResult(Activity.java:5527)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:761)
       at android.app.Activity.startActivity(Activity.java:6045)
       at android.app.Activity.startActivity(Activity.java:6012)
       at com.applovin.impl.adview.q.a(SourceFile:448)
       at com.applovin.impl.adview.q.a(SourceFile:52)
       at com.applovin.impl.adview.q$2$1.run(SourceFile:297)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
```
AppLovinSdk:shared_thread_pool:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1188)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:905)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012) 
```
```
AppLovinSdk:anr_detector:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:341)
       at android.os.Looper.loopOnce(Looper.java:168)
       at android.os.Looper.loop(Looper.java:299)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```
```
AppLovinSdk:network:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:549)
       at com.applovin.impl.sdk.network.e$a.a(SourceFile:98)
       at com.applovin.impl.sdk.network.e$a.run(SourceFile:85)
```
```
AppLovinSdk:auxiliary_operations:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1176)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:905)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```
