### ISSUE TITLE
App Crashes if  MAX SDK included, even without using the SDK anywhere

### ISSUE THREAD

**Issue by waqas-334** [AppLovin/AppLovin-MAX-SDK-Android#57]
Hey, I am trying to implement AppLovin SDK to my Android App. 

The app works perfectly fine but as soon as I follow the App Lovin's Android integration and add the dependencies accordingly to the build.gradle, and run the app. It crashes straight with the following logcat. Can you please help me out with this?

Thanks

`2021-11-19 23:40:36.590 7047-7047/com.androidbull.incognito.browser E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "com.androidbull.incognito.browser.androidx" on path: DexPathList[[zip file "/data/app/com.androidbull.incognito.browser-3EQ63i-16Gie0EJwJT27kA==/base.apk"],nativeLibraryDirectories=[/data/app/com.androidbull.incognito.browser-3EQ63i-16Gie0EJwJT27kA==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:256)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:855)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:950)
        at android.app.LoadedApk.getResources(LoadedApk.java:1188)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2462)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2454)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6343)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.androidbull.incognito.browser-3EQ63i-16Gie0EJwJT27kA==/base.apk because: Failure to verify dex file '/data/app/com.androidbull.incognito.browser-3EQ63i-16Gie0EJwJT27kA==/base.apk': Invalid type descriptor: ''
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:365)
        at dalvik.system.DexFile.<init>(DexFile.java:107)
        at dalvik.system.DexFile.<init>(DexFile.java:80)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:444)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:403)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:101)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:74)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:87)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:116)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:114)
        at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:60)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:851)
        		... 13 more
2021-11-19 23:40:36.604 7047-7047/com.androidbull.incognito.browser D/AndroidRuntime: Shutting down VM
2021-11-19 23:40:36.609 7047-7047/com.androidbull.incognito.browser E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.androidbull.incognito.browser, PID: 7047
    java.lang.RuntimeException: Unable to instantiate application com.androidbull.incognito.browser.App: java.lang.ClassNotFoundException: Didn't find class "com.androidbull.incognito.browser.App" on path: DexPathList[[zip file "/data/app/com.androidbull.incognito.browser-3EQ63i-16Gie0EJwJT27kA==/base.apk"],nativeLibraryDirectories=[/data/app/com.androidbull.incognito.browser-3EQ63i-16Gie0EJwJT27kA==/lib/x86, /system/lib, /system/product/lib]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1226)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.androidbull.incognito.browser.App" on path: DexPathList[[zip file "/data/app/com.androidbull.incognito.browser-3EQ63i-16Gie0EJwJT27kA==/base.apk"],nativeLibraryDirectories=[/data/app/com.androidbull.incognito.browser-3EQ63i-16Gie0EJwJT27kA==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1148)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1218)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.androidbull.incognito.browser-3EQ63i-16Gie0EJwJT27kA==/base.apk because: Failure to verify dex file '/data/app/com.androidbull.incognito.browser-3EQ63i-16Gie0EJwJT27kA==/base.apk': Invalid type descriptor: ''
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:365)
        at dalvik.system.DexFile.<init>(DexFile.java:107)
        at dalvik.system.DexFile.<init>(DexFile.java:80)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:444)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:403)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:101)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:74)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:87)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:116)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:114)
        at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:60)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:851)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:950)
        at android.app.LoadedApk.getResources(LoadedApk.java:1188)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2462)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2454)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6343)
        		... 8 more`

**Comment by applovinjosh** [comment]
@waqas-334 it looks like the issue might be related to the mixing of androidx libraries with older libraries. you can see it's trying to load an androidx class:  Didn't find class "com.androidbull.incognito.browser.androidx"
make sure you are fully migrated over to androidx and using the appropriate libraries.  [here are some docs](https://developer.android.com/jetpack/androidx/migrate) from google.
