### ISSUE TITLE
NullPointerException Crash when implementing Amazon SDK on emulator

### ISSUE THREAD

**Issue by tskiller1** [AppLovin/AppLovin-MAX-SDK-Android#595]
### MAX SDK Version

11.11.3

### Device/Platform Info

Android 12, Pixel 4

### Current Behavior

When I init Amazon SDK and run it on Emulator, Amazon SDK is not initialized and it crashes. But if run it on debug and set a breakpoint before init Amazon SDK then continue, it will run well. Besides, if run on real devices, it is okay and the status of Amazon SDK is initialized

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at com.applovin.impl.mediation.e.a(SourceFile:130)
at com.applovin.impl.mediation.e.a(SourceFile:118)
at com.applovin.impl.mediation.MediationServiceImpl.collectSignal(SourceFile:331)
at com.applovin.impl.mediation.c.b$1.run(SourceFile:222)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### How to Reproduce

init amazon SDK before init Applovin SDK and run it on the emulator of Android Studio

**Comment by alvarshahanji** [comment]
@tskiller1 what is the Amazon SDK/adapter version you are using?

**Comment by tskiller1** [comment]
@alvarshahanji I'm using this version 'com.applovin.mediation:amazon-tam-adapter:9.8.6.0'

**Comment by tskiller1** [comment]
@alvarshahanji  yes, sure ('com.amazon.android:aps-sdk:9.8.6')

**Comment by alvarshahanji** [comment]
Could you check if the issue is reproducible on our [demo app](https://github.com/AppLovin/AppLovin-MAX-SDK-Android), could you share the repro steps?
