### ISSUE TITLE
Attempting to show ad without a valid activity (java.lang.IllegalArgumentException)

### ISSUE THREAD

**Issue by mehmeteminyildiz** [AppLovin/AppLovin-MAX-SDK-Android#606]
### MAX SDK Version

12.1.0

### Device/Platform Info

On many devices

### Current Behavior

While showing or loading the Interstitial ad, I get the Attempting to show ad without a valid activity error. I'm running a foreground service. I show ads in certain situations. However, recently there has been an increase in this error.
Can you help me?

### Expected Behavior

Not receiving the Attempting to show ad without a valid activity error during the show and load phase, or explaining the situations that may cause this error.

### How to Reproduce

After the ad is loaded, the show is made.
Attention: This error is not encountered all the time. It is encountered occasionally when many attempts are made.

### Full Crash Log
Fatal Exception: java.lang.IllegalArgumentException: Attempting to show ad without a valid activity.
       at com.applovin.impl.mediation.ads.MaxFullscreenAdImpl.a(SourceFile:370)
       at com.applovin.impl.mediation.ads.MaxFullscreenAdImpl.showAd(SourceFile:253)
       at com.applovin.mediation.ads.MaxInterstitialAd.showAd(SourceFile:157)
       at com.applovin.mediation.ads.MaxInterstitialAd.showAd(SourceFile:140)
       at com.ibragunduz.applockpro.ads.AppLovinAdManager.showInterstitialAppplovin(AppLovinAdManager.kt:175)
       at com.ibragunduz.applockpro.ads.AppLovinAdManager.showInterstitial(AppLovinAdManager.kt:262)
       at com.ibragunduz.applockpro.ads.Ads$DefaultImpls.showInterstitial$default(Ads.kt:9)
       at com.ibragunduz.applockpro.ads.UseDropActivity.showInterstitial(UseDropActivity.kt:85)
       at com.ibragunduz.applockpro.ads.UseDropActivity$observeInterstitial$1.invoke(UseDropActivity.kt:68)
       at com.ibragunduz.applockpro.ads.UseDropActivity$observeInterstitial$1.invoke(UseDropActivity.kt:63)
       at com.ibragunduz.applockpro.ads.UseDropActivity.observeInterstitial$lambda$0(UseDropActivity.kt:63)
       at com.ibragunduz.applockpro.common.SingleLiveEvent$observe$1.onChanged(SingleLiveEvent.kt:27)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
       at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
       at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
       at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
       at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
       at android.app.Activity.dispatchActivityPostStarted(Activity.java:1278)
       at android.app.Activity.performStart(Activity.java:8018)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3472)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7807)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

_No response_

**Comment by thomasmso** [comment]
@mehmeteminyildiz - Some mediated networks require an `Activity` instance to be shown. In this case, the `Activity` instance that you initialized `MaxInterstitialAd` with had been deallocated. Do you have an active `Activity` instance when you call `MaxInterstitialAd#showAd(...)`?

**Comment by mehmetyildizeywin** [comment]
> @mehmeteminyildiz - Some mediated networks require an `Activity` instance to be shown. In this case, the `Activity` instance that you initialized `MaxInterstitialAd` with had been deallocated. Do you have an active `Activity` instance when you call `MaxInterstitialAd#showAd(...)`?

Thank you sir :)
