### ISSUE TITLE
Crash caused in Android app due to inMobi Banner

### ISSUE THREAD

**Issue by sjmach** [AppLovin/AppLovin-MAX-SDK-Android#620]
### MAX SDK Version

12.1.0

### Device/Platform Info

Android 12

### Current Behavior

![inmobi-error](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/303605/1e1754bc-4a47-4194-972b-90fcb8c53bce)

The android app crashes when I am using the latest adapter   'com.applovin.mediation:inmobi-adapter:10.6.3.0 with Applovin SDK 12.1.0

  E  FATAL EXCEPTION: main
                                                                                                    Process: XXXX, PID: 6593
                                                                                                    java.lang.VerifyError: Verifier rejected class com.inmobi.media.d6: java.lang.String com.inmobi.media.d6.getMaxSize(java.lang.String) failed to verify: java.lang.String com.inmobi.media.d6.getMaxSize(java.lang.String): [0x10C] expected to be within a catch-all for an instruction where a monitor is held (declaration of 'com.inmobi.media.d6' appears in /data/app/~~EBDk_qUkp7MbEPrGsxK6rw==/XXXX-KtSpYUrHU-eLBKofVdlUdw==/base.apk!classes7.dex)
                                                                                                    	at com.inmobi.media.cb.a(RenderView.kt:173)
                                                                                                    	at com.inmobi.ads.controllers.a.e(AdUnit.kt:37)
                                                                                                    	at com.inmobi.ads.controllers.a.s0(AdUnit.kt:3)
                                                                                                    	at com.inmobi.media.m1.g(BannerAdUnit.kt:277)
                                                                                                    	at com.inmobi.media.m1$$ExternalSyntheticLambda4.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

### How to Reproduce

1. Use latest Applovin SDK - 12.1.0 in build.gradle for your app
2. Also add    implementation 'com.applovin.mediation:inmobi-adapter:10.6.3.0'
    implementation 'com.squareup.picasso:picasso:2.71828'

3. Call a banner app using Applovin Creative Debugger or wait for a Banner request to be filled by inMobi

P.S. Use Applovin max as a Biidder

Also observed that Meta and admob ads are working fine

**Comment by alvarshahanji** [comment]
@sjmach could not reproduce the issue with Applovin SDK 12.1.0 and latest adapter 'com.applovin.mediation:inmobi-adapter:10.6.3.0'. Could you see if the issue is reproducible on our [demo app](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/tree/master/AppLovin%20MAX%20Demo%20App%20-%20Java)? Or please share a sample project where this is reproducible? Thanks!
