### ISSUE TITLE
java.lang.IllegalStateException: Failed to load new ad - this instance is already destroyed for ad unit ID

### ISSUE THREAD

**Issue by rosebm** [AppLovin/AppLovin-MAX-SDK-Android#623]
### MAX SDK Version

12.1.0

### Device/Platform Info

Android

### Current Behavior

The app is crashing, and checking the logcat it says: 
```
FATAL EXCEPTION: main
Process: com.adfone.aditup.staging, PID: 24960
 java.lang.IllegalStateException: Failed to load new ad - this instance is already destroyed for ad unit ID: 46fb000303d5239c
at com.applovin.impl.mediation.ads.MaxFullscreenAdImpl.loadAd(SourceFile:201)
at com.applovin.impl.mediation.ads.MaxFullscreenAdImpl.loadAd(SourceFile:182)
at com.applovin.mediation.ads.MaxRewardedAd.loadAd(SourceFile:113)
at com.adfone.cover.architecture.ui.containers.providers.managers.ApplovinAdManager.loadAd$lambda$0(ApplovinAdManager.kt:82)
at com.adfone.cover.architecture.ui.containers.providers.managers.ApplovinAdManager.$r8$lambda$j4XvL_MRYmXar7-ttACTf78IrVg(Unknown Source:0)
at com.adfone.cover.architecture.ui.containers.providers.managers.ApplovinAdManager$$ExternalSyntheticLambda0.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

I understand that on the latest version v12.1.0 a crash was fixed, but I am able to replicate it.

### Expected Behavior

The app doesn't crash

### How to Reproduce

Update SDK to v12.1.0
- Call showRewardedAd twice

**Comment by thomasmso** [comment]
@rosebm - This is expected behaviour. Whilst we might not crash in production builds, we will crash in dev builds if you attempt to call `loadAd()` on an ad instance that you have `destroy()`ed.

**Comment by MKelman** [comment]
Hi @thomasmso This is completely unacceptable. This breaks a lot of our QA tests. A crash should NEVER be "expected behavior" regardless of the environment. I would really hope you guys prioritize fixing this for all environments so we can bump up your sdk as this is a blocker for us to release as of now.

**Comment by thomasmso** [comment]
@MKelman - In this case, I would admit we should document the limitations of the `destroy()` and `loadAd()` API when used together - we'll call that out in our docs (cc @PLP-Consulting).

However, the alternative of not throwing an exception would be to either fail the ad loads or print some logs, which might've been easily missed. Would you be able to update your integration to avoid the crash?

**Comment by MKelman** [comment]
@thomasmso how sure are you that it wont throw an error in production? We could print some logs so it doesn't crash but we also dont want to lose revenue from not showing ads in our app in parts that it should show ads.

**Comment by thomasmso** [comment]
We check for the [FLAG_DEBUGGABLE](https://developer.android.com/reference/android/content/pm/ApplicationInfo#FLAG_DEBUGGABLE) flag first before throwing the exception. But yeah, def. something to fix as to not lose revenue.

**Comment by MKelman** [comment]
@thomasmso but you're saying the ultimate fix is something we need to do on our end? We need to be able to call loadAd after destroyAd though. We have different features that after one feature loads an ad and destroys the ad, we need to load another ad.

**Comment by thomasmso** [comment]
@MKelman - We'd recommend using the same instance of the `MaxRewardedAd` without destroying it in the first place.

**Comment by MKelman** [comment]
@thomasmso seems like after some change, i do see a new "silent crash". is this a different issue or connected?

org.json.JSONException: Value false at cache_file_ttl_seconds of type java.lang.Boolean cannot be converted to long
                                         	at org.json.JSON.typeMismatch(JSON.java:101)
                                         	at org.json.JSONObject.getLong(JSONObject.java:528)
                                         	at com.applovin.impl.sdk.c.c.a(SourceFile:310)
                                         	at com.applovin.impl.sdk.c.c.a(SourceFile:242)
                                         	at com.applovin.impl.sdk.utils.i.e(SourceFile:308)
                                         	at com.applovin.impl.sdk.o.a(SourceFile:946)
                                         	at com.applovin.impl.sdk.o.a(SourceFile:94)
                                         	at com.applovin.impl.sdk.o$12.a(SourceFile:797)
                                         	at com.applovin.impl.sdk.e.l.a(SourceFile:418)
                                         	at com.applovin.impl.sdk.e.l.a(SourceFile:36)
                                         	at com.applovin.impl.sdk.e.l$1.a(SourceFile:117)
                                         	at com.applovin.impl.sdk.e.l$1.a(SourceFile:113)
                                         	at com.applovin.impl.sdk.e.x$1.a(SourceFile:58)
                                         	at com.applovin.impl.sdk.network.b$b.a(SourceFile:355)
                                         	at com.applovin.impl.sdk.network.b$b.accept(SourceFile:242)
                                         	at com.applovin.impl.sdk.network.e$a$1.run(SourceFile:182)
                                         	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
                                         	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                         	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                         	at java.lang.Thread.run(Thread.java:923)
