### ISSUE TITLE
LINE adapter is not initialized.

### ISSUE THREAD

**Issue by takazawa-gg** [AppLovin/AppLovin-MAX-SDK-Android#646]
### MAX SDK Version

12.3.1

### Device/Platform Info

Android 13, Pixel 6a

### Current Behavior

LINE ads are not displayed.
An error will be displayed asking you to initialize first.

### Expected Behavior

LINE ads must be able to be displayed in test mode.

### How to Reproduce

Install LINE adapter v2024.2.14.0 (SDK: 2.7.20240214) and display a test ad.

### Additional Info

Android log file
[20240402_LINE_error_log.zip](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/14836777/20240402_LINE_error_log.zip)

![Screenshot_20240402-212256](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/65539801/32e55176-dc30-4d51-9e72-df4a0e266c91)

![Screenshot_20240402-212241](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/65539801/85daec68-d126-498e-bf9e-813584549e5e)

![Screenshot_20240402-212234](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/65539801/9ed28c9f-278f-4230-a77f-fc60edb8ad27)

**Comment by takazawa-gg** [comment]
I got the verbose log.
[20240403_LINE_verbose_log.zip](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/14849700/20240403_LINE_verbose_log.zip)

```
[MediationAdapterWrapper] LineMediationAdapter: running initialize...
[MediationAdapterWrapper] Initializing LineMediationAdapter on thread: Thread[main,5,main] with 'run_on_ui_thread' value: true
[LineMediationAdapter] Initializing Line SDK with app id: ***...
[MediationAdapterWrapper] Failed operation initialize for LINE_NATIVE_NETWORK
java.lang.IllegalStateException: call initialize() first.
	at com.five_corp.ad.t.a(Unknown Source:13)
	at com.five_corp.ad.z.a(Unknown Source:3)
	at com.five_corp.ad.z.a(Unknown Source:23)
	at com.five_corp.ad.FiveAd.initialize(Unknown Source:9)
	at com.applovin.mediation.adapters.LineMediationAdapter.initialize(LineMediationAdapter.java:120)
	at com.applovin.impl.mediation.g.a(SourceFile:160)
	at com.applovin.impl.mediation.g.$r8$lambda$P8ak0ZaNSX0dUWNUh9Eg6l9SdsE(Unknown Source:0)
	at com.applovin.impl.mediation.g$$ExternalSyntheticLambda1.run(Unknown Source:8)
	at com.applovin.impl.mediation.g.c(SourceFile:812)
	at com.applovin.impl.mediation.g.$r8$lambda$kxtVMnRNofoy57UlSq-gSaYdMQc(Unknown Source:0)
	at com.applovin.impl.mediation.g$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
[MediationAdapterWrapper] Marking LineMediationAdapter as disabled due to: fail_initialize
[MediationAdapterManager] Adding com.applovin.mediation.adapters.LineMediationAdapter to list of disabled adapters.
[MediationAdapterWrapper] LineMediationAdapter: running initialize...
[MediationAdapterWrapper] Initializing LineMediationAdapter on thread: Thread[main,5,main] with 'run_on_ui_thread' value: true
[LineMediationAdapter] Line SDK still initializing
[MediationAdapterWrapper] LineMediationAdapter: finished initialize
[ErrorReporter] Reporting caught_exception error...
```

**Comment by jplianghu** [comment]
@takazawa-gg 
It seems that the Line Ads SDK failed to initialize. Given that you're using a debug build and are in test mode, would
you try re-installing your app to clear any cached data saved by the Line Ads SDK. If this doesn't resolve the issue, we'll need to contact LINE for further investigation into the error occurring at `com.five_corp.ad.t.a(Unknown Source:13)`. 
It might also be worth trying to switch to live mode instead of test mode for ad loading.
