### ISSUE TITLE
Adapter Missing when integrating vungle-adapter:7.3.1.0

### ISSUE THREAD

**Issue by gzjaychen** [AppLovin/AppLovin-MAX-SDK-Android#652]
### MAX SDK Version

12.4.0

### Device/Platform Info

Android

### Current Behavior

MAX Mediation Debugger shows
Liftoff Monetize
SDK Found
Adapter Missing

### Expected Behavior

show Liftoff Adapter version

### How to Reproduce

implementation("com.applovin.mediation:vungle-adapter:7.3.1.0")

**Comment by jplianghu** [comment]
@gzjaychen this is fixed in v7.3.1.1, please upgrade your adapter version to latest.
implementation("com.applovin.mediation:vungle-adapter:7.3.1.1")

**Comment by gzjaychen** [comment]
> @gzjaychen this is fixed in v7.3.1.1, please upgrade your adapter version to latest. implementation("com.applovin.mediation:vungle-adapter:7.3.1.1")

Error occurred while instrumenting class com.applovin.mediation.adapters.VungleMediationAdapter$1

Caused by: java.lang.RuntimeException: Error occurred while instrumenting class com.applovin.mediation.adapters.VungleMediationAdapter$1
	at com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.doInstrumentClass(AsmInstrumentationManager.kt:292)
	at com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.instrumentClassToJar(AsmInstrumentationManager.kt:344)
	at com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.instrumentClassesFromJarToJar(AsmInstrumentationManager.kt:158)
	at com.android.build.gradle.internal.dependency.AsmClassesTransform.transform(AsmClassesTransform.kt:141)
	at org.gradle.api.internal.artifacts.transform.DefaultTransform.transform(DefaultTransform.java:278)
	at org.gradle.api.internal.artifacts.transform.AbstractTransformExecution$2.call(AbstractTransformExecution.java:138)
	at org.gradle.api.internal.artifacts.transform.AbstractTransformExecution$2.call(AbstractTransformExecution.java:132)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:78)
	at org.gradle.api.internal.artifacts.transform.AbstractTransformExecution.executeWithinTransformerListener(AbstractTransformExecution.java:132)
	at org.gradle.api.internal.artifacts.transform.AbstractTransformExecution.execute(AbstractTransformExecution.java:125)
	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:78)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:28)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:100)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:72)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:50)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:179)
	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:70)
	at org.gradle.internal.Either$Right.fold(Either.java:175)
	at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:68)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:46)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:91)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:55)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:37)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:77)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:38)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:108)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:55)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:71)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:45)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNonEmptySources(SkipEmptyWorkStep.java:177)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:81)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:53)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
	at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:75)
	at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:41)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$0(ExecuteWorkBuildOperationFiringStep.java:52)
	at org.gradle.internal.execution.steps.BuildOperationStep$1.call(BuildOperationStep.java:37)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:78)
	at org.gradle.internal.execution.steps.BuildOperationStep.operation(BuildOperationStep.java:34)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$1(ExecuteWorkBuildOperationFiringStep.java:50)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:50)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:38)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:32)
	at org.gradle.internal.execution.workspace.impl.DefaultImmutableWorkspaceProvider.lambda$withWorkspace$3(DefaultImmutableWorkspaceProvider.java:140)
	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:90)
	at org.gradle.cache.internal.DefaultCacheCoordinator.withFileLock(DefaultCacheCoordinator.java:219)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:179)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:214)
	at org.gradle.internal.execution.workspace.impl.DefaultImmutableWorkspaceProvider.withWorkspace(DefaultImmutableWorkspaceProvider.java:137)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:21)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
	at org.gradle.internal.execution.steps.IdentityCacheStep.lambda$executeDeferred$0(IdentityCacheStep.java:49)
	at org.gradle.cache.Cache.lambda$get$0(Cache.java:31)
	at org.gradle.cache.ManualEvictionInMemoryCache.get(ManualEvictionInMemoryCache.java:30)
	at org.gradle.cache.internal.DefaultCrossBuildInMemoryCacheFactory$CrossBuildCacheRetainingDataFromPreviousBuild.get(DefaultCrossBuildInMemoryCacheFactory.java:255)
	at org.gradle.cache.Cache.get(Cache.java:31)
	at org.gradle.internal.execution.steps.IdentityCacheStep.lambda$executeDeferred$1(IdentityCacheStep.java:47)
	at org.gradle.internal.Deferrable$3.completeAndGet(Deferrable.java:117)


Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.doInstrumentByteCode(AsmInstrumentationManager.kt:200)
	at com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.doInstrumentClass(AsmInstrumentationManager.kt:257)

**Comment by MichaelPlan** [comment]
WIth v7.3.1.1 I get: Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.applovin.mediation:vungle-adapter:7.3.1.1, variant=com.applovin.mediation:vungle-adapter:7.3.1.1 configuration compile, variantName=null, artifactFile=/Users/username/.gradle/caches/modules-2/files-2.1/com.applovin.mediation/vungle-adapter/7.3.1.1/b8fe21feaba1a456655df8f9b76379d022572d4c/vungle-adapter-7.3.1.1.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping=...

**Comment by gzjaychen** [comment]
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65

Recompile with a lower version of the jdk  is OK.
@jplianghu

**Comment by centy** [comment]
Same problem: 

> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform vungle-adapter-7.3.1.1.aar (com.applovin.mediation:vungle-adapter:7.3.1.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\jacek\.gradle\caches\modules-2\files-2.1\com.applovin.mediation\vungle-adapter\7.3.1.1\b8fe21feaba1a456655df8f9b76379d022572d4c\vungle-adapter-7.3.1.1.aar.
         > Failed to transform 'C:\Users\jacek\.gradle\caches\modules-2\files-2.1\com.applovin.mediation\vungle-adapter\7.3.1.1\b8fe21feaba1a456655df8f9b76379d022572d4c\vungle-adapter-7.3.1.1.aar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 65. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

**Comment by Jun19** [comment]
> > @gzjaychen此问题已在 v7.3.1.1 中修复，请将您的适配器版本升级到最新版本。实现（“com.applovin.mediation：vungle-adapter：7.3.1.1”）
> 
> 检测类 com.applovin.mediation.adapters.VungleMediationAdapter$1 时发生错误
> 
> 原因：java.lang.RuntimeException：在 com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.doInstrumentClass(AsmInstrumentationManager.kt:292)处检测类 com.applovin.mediation.adapters.VungleMediationAdapter$1 时发生错误 。 android.build.gradle.internal.instrumentation.AsmInstrumentationManager.instrumentClassToJar（AsmInstrumentationManager.kt：344） 在com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.instrumentClassesFromJarToJar（AsmInstrumentationManager.kt：158） 在com.android.build。 gradle.internal.dependency.AsmClassesTransform.transform（AsmClassesTransform.kt：141） 在org.gradle.api.internal.artifacts.transform.DefaultTransform.transform（DefaultTransform.java：278） 在org.gradle.api.internal.artifacts。 在 org.gradle.api.internal.artifacts.transform.AbstractTransformExecution$2.call(AbstractTransformExecution.java:132) 在 org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker 处调用（AbstractTransformExecution.java:138） 。执行（DefaultBuildOperationRunner.java:204） 在org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute（DefaultBuildOperationRunner.java:199） 在org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute（DefaultBuildOperationRunner.java:66） 在org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59) 在 org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157) 在 org.gradle.internal.operations.DefaultBuildOperationRunner.execute (DefaultBuildOperationRunner.java:59) 在 org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53) 在 org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:78) 在 org.gradle。 api.internal.artifacts.transform.AbstractTransformExecution.executeWithinTransformerListener(AbstractTransformExecution.java:132) 在 org.gradle.api.internal.artifacts.transform.AbstractTransformExecution.execute(AbstractTransformExecution.java:125) 在 org.gradle.internal.execution。步骤.ExecuteStep.executeInternal(ExecuteStep.java:105) 在 org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44) 在 org.gradle.internal.execution.steps.ExecuteStep$1.call( ExecuteStep.java:59) 在 org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56) 在 org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204) 在 org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199) 在 org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66) 在 org.gradle.internal.operations。 DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59) 在 org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157) 在 org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59) 在org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53) 在 org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:78) 在 org.gradle.internal.execution.steps.ExecuteStep。 在 org.gradle.internal.execution.steps.execute(ExecuteStep.java:44) 在 org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)处执行（ExecuteStep.java:56） 在 org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37) 在 org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41) 在 org.gradle.internal.execution .steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74) 在 org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55) 在 org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep .java:50) 在 org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:28) 在 org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:100) 在 org. gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:72) 在 org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:50) 在 org.gradle.internal.execution.steps。 ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40) 在 org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29) 在 org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java: 179) 在 org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:70) 在 org.gradle.internal.Either$Right.fold(Either.java:175) 在 org.gradle。 org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:68) 处的internal.execution.caching.CachingState.fold(CachingState.java:59 ) 在 org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:46) 在 org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36) 在 org.gradle.internal.execution .steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25) 在 org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36) 在 org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep) .java:22) 在 org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:91) 在 org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:55) 在 org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55) 在 org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:37) 在 org.gradle.internal.execution .steps.ResolveChangesStep.execute(ResolveChangesStep.java:65) 在 org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36) 在 org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute (MarkSnapshottingInputsFinishedStep.java:37) 在 org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27) 在 org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:77) ） 在org.gradle.internal.execution.steps.ResolveCachingStateStep.execute（ResolveCachingStateStep.java:38） 在org.gradle.internal.execution.steps.ValidateStep.execute（ValidateStep.java:108） 在org.gradle.internal。 execution.steps.ValidateStep.execute(ValidateStep.java:55) 在 org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:71) 在 org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute( CaptureStateBeforeExecutionStep.java:45) 在 org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNonEmptySources(SkipEmptyWorkStep.java:177) 在 org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:81) 在 org .gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:53) 在 org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32) 在 org.gradle.internal.execution.steps .RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21) 在 org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38) 在 org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36) 在 org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23) 在 org.gradle.internal.execution .steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:75) 在 org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:41) 在 org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute $0(ExecuteWorkBuildOperationFiringStep.java:52) 在 org.gradle.internal.execution.steps.BuildOperationStep$1.call(BuildOperationStep.java:37) 在 org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204 ） 在 org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199) 在 org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66) 在 org.gradle.internal.operations .DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59) 在 org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157) 在 org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59) 在 org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53) 在 org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:78) 在 org.gradle.internal.execution.steps.BuildOperationStep .operation(BuildOperationStep.java:34) 在 org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$1(ExecuteWorkBuildOperationFiringStep.java:50) 在 org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep. java:50) 在 org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:38) 在 org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:32) 在org.gradle.internal.execution.workspace.impl.DefaultImmutableWorkspaceProvider.lambda$withWorkspace$3(DefaultImmutableWorkspaceProvider.java:140) 在 org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:90) 在 org.gradle.cache .internal.DefaultCacheCoordinator.withFileLock(DefaultCacheCoordinator.java:219) 在 org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:179) 在 org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:214) 在 org.gradle.internal.execution.workspace.impl.DefaultImmutableWorkspaceProvider.withWorkspace(DefaultImmutableWorkspaceProvider.java:137) 在 org.gradle.internal .execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30) 在 org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:21) 在 org.gradle.internal.execution.steps.IdentityCacheStep.execute (IdentityCacheStep.java:37) 在 org.gradle.internal.execution.steps.IdentityCacheStep.lambda$executeDeferred$0(IdentityCacheStep.java:49) 在 org.gradle.cache.Cache.lambda$get$0(Cache.java:31) ） 在 org.gradle.cache.ManualEvictionInMemoryCache.get（ManualEvictionInMemoryCache.java:30） 在 org.gradle.cache.internal.DefaultCrossBuildInMemoryCacheFactory$CrossBuildCacheRetainingDataFromPreviousBuild.get（DefaultCrossBuildInMemoryCacheFactory.java:255） 在 org.gradle.cache.Cache.get（ Cache.java:31) 在 org.gradle.internal.execution.steps.IdentityCacheStep.lambda$executeDeferred$1(IdentityCacheStep.java:47) 在 org.gradle.internal.Deferrable$3.completeAndGet(Deferrable.java:117)
> 
> 引起原因：java.lang.IllegalArgumentException：在 org.objectweb.asm.ClassReader.(ClassReader.java:199) 处，org.objectweb.asm.ClassReader.(ClassReader.java:180) 处不支持类文件主要版本 65 。 objectweb.asm.ClassReader.(ClassReader.java:166) 在 com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager.doInstrumentByteCode(AsmInstrumentationManager.kt:200) 在 com.android.build.gradle.internal.instrumentation.AsmInstrumentationManager .doInstrumentClass(AsmInstrumentationManager.kt:257)

Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.applovin.mediation:fyber-adapter:8.2.7.0, variant=com.applovin.mediation:fyber-adapter:8.2.7.0 configuration compile, variantName=null, artifactFile=/Users/yuanjunjie/.gradle/caches/modules-2/files-2.1/com.applovin.mediation/fyber-adapter/8.2.7.0/193850b1eb44f730942645046e31133930b71e7c/fyber-adapter-8.2.7.0.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false)

**Comment by jplianghu** [comment]
@Jun19 @centy 
We've released v7.3.1.2 with a fix for the build errors, could you try that?

**Comment by gzjaychen** [comment]
> @Jun19 @centy We've released v7.3.1.2 with a fix for the build errors, could you try that?

It works

**Comment by Jun19** [comment]
> @Jun19 @centy 我们已经发布了 v7.3.1.2，修复了构建错误，您可以尝试一下吗？

vungle v7.3.1.2 work
Bug the same issue occurred in com. applovin. media: fber adapter: 8.2.7.0

Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.applovin.mediation:fyber-adapter:8.2.7.0, variant=com.applovin.mediation:fyber-adapter:8.2.7.0 configuration compile, variantName=null, artifactFile=/Users/yuanjunjie/.gradle/caches/modules-2/files-2.1/com.applovin.mediation/fyber-adapter/8.2.7.0/193850b1eb44f730942645046e31133930b71e7c/fyber-adapter-8.2.7.0.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false)

**Comment by MichaelPlan** [comment]
> @Jun19 @centy We've released v7.3.1.2 with a fix for the build errors, could you try that?

It works for me, too.

**Comment by jplianghu** [comment]
> Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.applovin.mediation:fyber-adapter:8.2.7.0, variant=com.applovin.mediation:fyber-adapter:8.2.7.0 configuration compile, variantName=null, artifactFile=/Users/yuanjunjie/.gradle/caches/modules-2/files-2.1/com.applovin.mediation/fyber-adapter/8.2.7.0/193850b1eb44f730942645046e31133930b71e7c/fyber-adapter-8.2.7.0.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false)

@Jun19 Please also upgrade fyber-adapter to 8.2.7.1.
