### ISSUE TITLE
NullPointerException: com.applovin.adview.AppLovinFullscreenActivity.onDestroy(SourceFile:1)

### ISSUE THREAD

**Issue by harinlin** [AppLovin/AppLovin-MAX-SDK-Android#664]
### MAX SDK Version

12.4.3

### Device/Platform Info

Android

### Current Behavior

**Crash log:** 
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.applovin.impl.sdk.k.a(com.applovin.impl.oj)' on a null object reference
       at com.applovin.adview.AppLovinFullscreenActivity.onDestroy(SourceFile:1)
       at android.app.Activity.performDestroy(Activity.java:9274)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1491)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6135)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6180)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8918)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

### Expected Behavior

Please fixed this issue as soon as possible, it is top 1 issues
Your sdk make us upset, every new version comes out, always has cristical issues

### How to Reproduce

Crash a lot when use new applovin sdk : 12.4.3

**Comment by harinlin** [comment]
@cemtuver-applovin  has any suggestions?

**Comment by cemtuver-applovin** [comment]
Hey @harinlin! Thank you for reporting this issue. We are already looking at it and will keep you updated on our progress.

**Comment by duydv0311** [comment]
I have a same issue like you @harinlin , please fix as soon as possible @cemtuver-applovin

**Comment by donha1** [comment]
see high volume of this issue reported via firebase, after updating to 12.4.3

**Comment by cutler** [comment]
It's been almost a week and I still haven't finished it. I don't need Max anymore. I'll switch to admob. You guys are too amateur, really!

**Comment by harinlin** [comment]
> It's been almost a week and I still haven't finished it. I don't need Max anymore. I'll switch to admob. You guys are too amateur, really!

agree!! and always has cristical issues

**Comment by JimRaid** [comment]
It's an early crash for us. So < 1 second runtime. Hope this helps.

And I agree I updated MaxSDK 2 times now and did hotfixes on my app just to find out there is a new crash.
Please double down your Investments into QA.

**Comment by zhaomf-hippo** [comment]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.applovin.impl.sdk.k.a(com.applovin.impl.oj)' on a null object reference

crash error log....


all QA are intern? 
or No More QA to test?
or your DevOps pipeline break?

**Comment by chad171** [comment]
This is an issue for us as well. Is 12.4.2 more stable?

**Comment by thomasmso** [comment]
We just pushed Android SDK v12.5.0 which resolves this issue.
