### ISSUE TITLE
google-adapter dependency 

### ISSUE THREAD

**Issue by Jun19** [AppLovin/AppLovin-MAX-SDK-Android#665]
### MAX SDK Version

12.4.3

### Device/Platform Info

Android13、PIXEL4

### Current Behavior

  1.  Dependency 'androidx.webkit:webkit:1.11.0-alpha02' requires libraries and applications that
      depend on it to compile against version 34 or later of the
      Android APIs.

      :app is currently compiled against android-33.

      Recommended action: Update this project to use a newer compileSdk
      of at least 34, for example 34.

      Note that updating a library or application's compileSdk (which
      allows newer APIs to be used) can be done separately from updating
      targetSdk (which opts the app in to new runtime behavior) and
      minSdk (which determines which devices the app can be installed
      on).
	at com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction.execute(CheckAarMetadataTask.kt:226)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:78)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:170)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:187)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:120)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:162)
	at org.gradle.internal.Factories$1.create(Factories.java:31)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:264)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:128)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:133)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:157)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:126)
	... 2 more

### Expected Behavior

support version 33 

### How to Reproduce

    implementation("com.applovin.mediation:google-adapter:23.1.0.0")

**Comment by DuyTuanDev** [comment]
Is there any way to fix it? I'm experiencing it. Thank.

**Comment by Jun19** [comment]
> Is there any way to fix it? I'm experiencing it. Thank.

This method can only be used for temporary resolution

configurations.configureEach {
    resolutionStrategy {
        force 'com.applovin.mediation:google-adapter:23.0.0.1'
        force 'com.applovin.mediation:google-ad-manager-adapter:23.0.0.1'
    }
}

**Comment by DuyTuanDev** [comment]
> > Có cách nào để sửa nó k? Tôi đang trải nghiệm nó. Cám ơn.
> 
> Phương pháp này chỉ có thể được sử dụng để giải quyết tạm thời
> 
> configures.configureEach { Độ phân giảiStrategy { Force 'com.applovin.mediation:google-adapter:23.0.0.1' Force 'com.applovin.mediation:google-ad-manager-adapter:23.0.0.1' } }

Thanks. I am looking for a solution by downgrading
google-ad-manager-adapter and google-adapter to version: Android-23.0.0.1-iOS-11.2.0.0
Builded successfully.

**Comment by DuyTuanDev** [comment]
> > Is there any way to fix it? I'm experiencing it. Thank.
> 
> This method can only be used for temporary resolution
> 
> configurations.configureEach { resolutionStrategy { force 'com.applovin.mediation:google-adapter:23.0.0.1' force 'com.applovin.mediation:google-ad-manager-adapter:23.0.0.1' } }

Thanks. Solution by downgrading
google-ad-manager-adapter and google-adapter to version: Android-23.0.0.1-iOS-11.2.0.0
Builded successfully.
