### ISSUE TITLE
Fatal Exception: java.nio.channels.OverlappingFileLockException

### ISSUE THREAD

**Issue by V-Beyond** [AppLovin/AppLovin-MAX-SDK-Android#670]
### MAX SDK Version

12.4.3

### Device/Platform Info

Galaxy A50，Android 11

### Current Behavior

After I connected to the Applovin SDK, the online version without the Applovin SDK did not throw this exception. The online version with Applovin started throwing Fatal Exception: java. nio. channels OverlappingFileLockException.

This is the specific log:
      Fatal Exception: java.nio.channels.OverlappingFileLockException:
       at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
       at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
       at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1174)
       at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
       at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle6432.aab-stable-636717933:84)
       at org.chromium.android_webview.AwBrowserProcess.j(chromium-TrichromeWebViewGoogle6432.aab-stable-636717933:16)
       at com.android.webview.chromium.L.d(chromium-TrichromeWebViewGoogle6432.aab-stable-636717933:203)
       at WV.QY.run(chromium-TrichromeWebViewGoogle6432.aab-stable-636717933:8)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

### How to Reproduce

Occurred under normal use by online users

**Comment by thomasmso** [comment]
@V-Beyond - Thanks for reporting this issue. How do you know it is derived from AppLovin SDK and not another SDK? What % of DAUs is crashing? Is it only on Galaxy A50, Android 11 (and thus, reproducible)?

**Comment by V-Beyond** [comment]
What I am certain of is that this issue occurred after I connected to the Applovin SDK, which was originally connected to Applovin, AdMob，pangle，inmobi， Xiaomi, OPPO， Other Samsung models also have this issue, occurring hundreds of times, with Samsung accounting for 43%.

**Comment by thomasmso** [comment]
@V-Beyond - Could you enable a potential fix in our SDK, via the following code snippet and report back?

```
AppLovinSdk sdk = AppLovinSdk.getInstance( context );
sdk.getSettings().setExtraParameter( "disable_set_data_dir_suffix", "true" );
...
```

**Comment by V-Beyond** [comment]
Thank you very much. In the next version, I will add this code and see the results of the online version to give you feedback.

**Comment by jokhjheds** [comment]
@V-Beyond  Is this problem solved?

**Comment by V-Beyond** [comment]
I'm sorry that I didn't give you feedback in time. I added sdk.getSettings().setExtraParameter( "disable_set_data_dir_suffix", "true" ) to the code, but the online feedback still shows the problem reported. But I'm sure this problem only appeared after adding the advertising SDK, so I don't know how to solve this problem now. Can you give me some other solutions?

**Comment by thomasmso** [comment]
@V-Beyond - my solution above should solve it for crashes originating from AppLovin SDK / network, are you able to re-confirm the source of the crash?

**Comment by SzymonGajdzica** [comment]
Any updates on this issue? I also expierience this error
