### ISSUE TITLE
The application crashes when an ad comes from Vungle mediation.

### ISSUE THREAD

**Issue by omeratesss** [AppLovin/AppLovin-MAX-SDK-Android#732]
### MAX SDK Version

12.5.0

### Device/Platform Info

Xiaomi 13 lite - android 14

### Crashes/ANRs per Day

12000

### Percentage of Users Affected

%89

### First Occurrence of Crash/ANR

Crashes started after adding Liftoff Monetize adapter library.

Note: Crash occurs both within the application and in the Mediation Debugger when ads from Liftoff Monetize are displayed. I would like to point out that this same crash happens sometimes with interstitial, sometimes with native, and sometimes with banner ads.

### Exception and Stack Trace

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/vungle/ads/internal/omsdk/Res;
    at com.vungle.ads.internal.omsdk.OMInjector.injectJsFiles(:35)
    at com.vungle.ads.internal.load.BaseAdLoader.processVmTemplate(:375)
    at com.vungle.ads.internal.load.BaseAdLoader.access$processVmTemplate(:41)
    at com.vungle.ads.internal.load.BaseAdLoader$assetDownloadListener$1.onSuccess$lambda-1(:161)
    at com.vungle.ads.internal.load.BaseAdLoader$assetDownloadListener$1.$r8$lambda$FVOSxFzi5I0wK3JuQHaRGbcGK30(:65354)
    at com.vungle.ads.internal.load.BaseAdLoader$assetDownloadListener$1$$ExternalSyntheticLambda1.run(:65353)
    at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion.wrapRunnableWithFail(:36)
    at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion.access$wrapRunnableWithFail(:31)
    at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion$getWrappedRunnableWithFail$2.run(:67)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.ClassNotFoundException: com.vungle.ads.internal.omsdk.Res
    at com.vungle.ads.internal.omsdk.OMInjector.injectJsFiles(:35)
    at com.vungle.ads.internal.load.BaseAdLoader.processVmTemplate(:375)
    at com.vungle.ads.internal.load.BaseAdLoader.access$processVmTemplate(:41)
    at com.vungle.ads.internal.load.BaseAdLoader$assetDownloadListener$1.onSuccess$lambda-1(:161)
    at com.vungle.ads.internal.load.BaseAdLoader$assetDownloadListener$1.$r8$lambda$FVOSxFzi5I0wK3JuQHaRGbcGK30(:65354)
    at com.vungle.ads.internal.load.BaseAdLoader$assetDownloadListener$1$$ExternalSyntheticLambda1.run(:65353)
    at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion.wrapRunnableWithFail(:36)
    at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion.access$wrapRunnableWithFail(:31)
    at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion$getWrappedRunnableWithFail$2.run(:67)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
`

### How to Reproduce

- Build a release APK (using ProGuard, DexGuard, etc.)
- Open the application.
- Open the MAX Mediation Debugger.
- Activate Test Mode.
- Go to the Liftoff Monetize network.
- Click on Test Mode.
- Try loading banner, interstitial, native, etc. ads. The application will crash and restart.

### Reproducible in the demo app?

Yes

### Additional Info

https://github.com/user-attachments/assets/b9ba31af-8fa5-444c-8ea8-06afd9ed79e6

**Comment by applovinAsh** [comment]
@omeratesss - I am unable to recreate the issue using Liftoff Adapter 7.4.1.2. Please consider updating your adapter to the latest version. You should also report the crash to Liftoff as it comes from their SDK.

**Comment by omeratesss** [comment]
@applovinAsh Why am I reporting this crash? This crash is also happening in your Applovin Debugger. I sent a video.

**Comment by applovinAsh** [comment]
As I stated previously, we are unable to recreate the crash. The provided stack trace shows the crash is coming from Liftoff's SDK and should be reported to them so they can fix it.
