### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by mituldevstree** [AppLovin/AppLovin-MAX-SDK-Android#733]
### MAX SDK Version

13.0.0

### Device/Platform Info

Samsung

### Crashes/ANRs per Day

10000

### Percentage of Users Affected

100%

### First Occurrence of Crash/ANR

Its crash on every start of the app

### Exception and Stack Trace

FairBid has encountered an error and is shutting down in 5 seconds. (Ask Gemini)
                 java.lang.NoSuchMethodError: No static method setIsAgeRestrictedUser(ZLandroid/content/Context;)V in class Lcom/applovin/sdk/AppLovinPrivacySettings; or its super classes (declaration of 'com.applovin.sdk.AppLovinPrivacySettings' appears in /data/app/~~WiqTrA6daDsxjM6ExWnw4w==/com.your.fantastic.pet-murRZGC-DlQsykKTgPxQkQ==/base.apk!classes2.dex)
                 	at com.fyber.fairbid.sdk.mediation.adapter.applovin.AppLovinAdapter.onStart(SourceFile:32)
                 	at com.fyber.fairbid.mediation.abstr.NetworkAdapter.a(SourceFile:5)
                 	at com.fyber.fairbid.mediation.abstr.NetworkAdapter$$ExternalSyntheticLambda5.run(Unknown Source:2)
                 	at com.fyber.fairbid.mo.run(SourceFile:1)
                 	at com.fyber.fairbid.mo.run(SourceFile:1)
                 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
                 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                 	at java.lang.Thread.run(Thread.java:923)

### How to Reproduce

On init the adapters

### Reproducible in the demo app?

Not Tested

**Comment by applovinAsh** [comment]
@mituldevstree—SDK 13.0.0 had a critical change that requires updating to a recent version. Please make sure you update your DTExchange adapter to 8.3.1.1 or newer. You will also have to do this for all other adapters.

**Comment by Mecze** [comment]
@applovinAsh Hi! Thanks for the response here. But I cannot find context why is COPPA removed from the plugin and all mediations. Just curiosity

Thanks!

**Comment by thomasmso** [comment]
@Mecze - We are strategically being more selective with the cohort of users that we want to serve to. We are unable to comment further.
