### ISSUE TITLE
Inmobi crashes with applovin gradle plugin enabled

### ISSUE THREAD

**Issue by mohamedsaber00** [AppLovin/AppLovin-MAX-SDK-Android#749]
### MAX SDK Version

13.0.1

### Device/Platform Info

Android 14, Pixel 8 pro

### Crashes/ANRs per Day

350 Event for 10% of users in one day

### Percentage of Users Affected

97%

### First Occurrence of Crash/ANR

When I updated from applovin 12.2.0 to 13.0.0 and inmboi adapter from 10.7.4.0 to 10.7.7.2

### Exception and Stack Trace

```
FATAL EXCEPTION: main
                         Process: com.megalol.app, PID: 23266
 java.lang.VerifyError: Verifier rejected class com.inmobi.media.ya: void com.inmobi.media.ya.a(com.inmobi.media.Aa, com.inmobi.commons.core.configs.AdConfig) failed to verify: void com.inmobi.media.ya.a(com.inmobi.media.Aa, com.inmobi.commons.core.configs.AdConfig): [0x299] cannot access instance field int com.inmobi.media.K1.b from object of type Unresolved Reference: com.inmobi.media.za (declaration of 'com.inmobi.media.ya' appears in /data/app/~~HM7jTAl8_aXId7gtvUlQNw==/com.megalol.app-siOaGYY8wLfsHyF14A-c3Q==/base.apk!classes3.dex)
                                                                                                    	at com.inmobi.media.E0.e(SourceFile:612)
                                                                                                    	at com.inmobi.media.E0.s0(SourceFile:1241)
                                                                                                    	at com.inmobi.media.w5.e(SourceFile:2)
                                                                                                    	at com.inmobi.media.w5$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### How to Reproduce

1. Download the applovin SDK sample in Kotlin
2. Update applovin and add inmobi adapter
3. Add applovin-quality-service 
4. Increase compile sdk to 35
5. Run the app and use mediation debugger to load inmobi interstitial ad

### Reproducible in the demo app?

Yes

**Comment by mohamedsaber00** [comment]
Fixed after updating Applovin gradle plugin
