### ISSUE TITLE
com.safedk.android.analytics.brandsafety.c.h ANR triggered by main thread being blocked

### ISSUE THREAD

**Issue by JimRaid** [AppLovin/AppLovin-MAX-SDK-Android#761]
### MAX SDK Version

13.0.1

### Device/Platform Info

All

### Crashes/ANRs per Day

35

### Percentage of Users Affected

0.1%

### First Occurrence of Crash/ANR

It actually occured the first time after update Firebase to Version v12.4.1.

### Exception and Stack Trace

```
          main (blocked):tid=1 systid=24776 | waiting to lock <0x083d2550> (com.safedk.android.analytics.brandsafety.InterstitialInfo) held by thread 88
       at com.safedk.android.analytics.brandsafety.c.h(SourceFile:261)
       at com.safedk.android.analytics.brandsafety.c.l(SourceFile:323)
       at com.safedk.android.analytics.brandsafety.InterstitialInfo.toString(SourceFile:118)
       at java.lang.String.valueOf(String.java:2924)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at com.safedk.android.analytics.brandsafety.InterstitialFinder.d(SourceFile:1811)
       at com.safedk.android.analytics.brandsafety.InterstitialFinder.g(SourceFile:3028)
       at com.safedk.android.internal.b.b(SourceFile:326)
       at com.safedk.android.internal.b.onActivityStopped(SourceFile:280)
       at android.app.Application.dispatchActivityStopped(Application.java:493)
       at android.app.Activity.dispatchActivityStopped(Activity.java:1566)
       at android.app.Activity.onStop(Activity.java:2793)
       at com.mbridge.msdk.reward.player.MBRewardVideoActivity.onStop(MBRewardVideoActivity.java:36)
       at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1546)
       at android.app.Activity.performStop(Activity.java:8601)
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5494)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5474)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5543)
       at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2441)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8396)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
        
```

```
          pool-67-thread-1 (blocked):tid=89 systid=25890 | waiting to lock <0x083d2550> (com.safedk.android.analytics.brandsafety.InterstitialInfo) held by thread 88
       at com.safedk.android.analytics.brandsafety.c.h(SourceFile:261)
       at com.safedk.android.analytics.brandsafety.c.l(SourceFile:323)
       at com.safedk.android.analytics.brandsafety.InterstitialInfo.toString(SourceFile:118)
       at java.lang.String.valueOf(String.java:2924)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at com.safedk.android.analytics.brandsafety.InterstitialFinder.a(SourceFile:1261)
       at com.safedk.android.analytics.brandsafety.InterstitialFinder.a(SourceFile:1224)
       at com.safedk.android.analytics.brandsafety.InterstitialFinder.f(SourceFile:1081)
       at com.safedk.android.analytics.brandsafety.InterstitialFinder.a(SourceFile:58)
       at com.safedk.android.analytics.brandsafety.InterstitialFinder$3.run(SourceFile:776)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:922)
```
        
        
                 ```
pool-21-thread-2 (blocked):tid=88 systid=25369 | waiting to lock <0x013a0773> (com.safedk.android.analytics.brandsafety.InterstitialFinder) held by thread 89
       at com.safedk.android.analytics.brandsafety.InterstitialFinder.a(SourceFile:1216)
       at com.safedk.android.analytics.brandsafety.InterstitialFinder.e(SourceFile:3200)
       at com.safedk.android.analytics.brandsafety.InterstitialFinder.b(SourceFile:2349)
       at com.safedk.android.analytics.brandsafety.InterstitialFinder.a(SourceFile:2331)
       at com.safedk.android.analytics.brandsafety.InterstitialFinder.a(SourceFile:2206)
       at com.safedk.android.analytics.brandsafety.creatives.CreativeInfoManager.a(SourceFile:1645)
       at com.safedk.android.analytics.brandsafety.creatives.discoveries.d.a(SourceFile:1915)
       at com.safedk.android.analytics.brandsafety.creatives.CreativeInfoManager$17.run(SourceFile:1538)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:922)
```
        
[com.iterationone.nightclubtycoon_issue_fc8f647302ae24b77046830a0f01dcea_ANR_session_675DD696019B000160C8262CEA811D7B_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/18137768/com.iterationone.nightclubtycoon_issue_fc8f647302ae24b77046830a0f01dcea_ANR_session_675DD696019B000160C8262CEA811D7B_DNE_0_v2_stacktrace.txt)

### How to Reproduce

We are using latest Applovin SDK v8.01 Android v13.0.1.
This issue first started to appear with updating Firebase to v12.5.0.
There seems to be an issue between both SDKs mainly Safedk.

### Reproducible in the demo app?

Not Tested

**Comment by NanaAmoah** [comment]
Hi @JimRaid, what Ad Review version are you using?

**Comment by JimRaid** [comment]
Hey @NanaAmoah, I'm using the Unity Package where can I find the version? There is no Ad Review in the integration manager displayed?

**Comment by JimRaid** [comment]
Ok we are still on v5.6.4 that explains it, but I have the issue that new builds don't have an updated version.
I did a "Force Resolve" with the External Dependency Manager. Any way to make it use the new version?

**Comment by NanaAmoah** [comment]
@JimRaid Did you see any errors in Unity when building the app?

**Comment by JimRaid** [comment]
@NanaAmoah I didn’t encounter any errors during the build. As a workaround, I manually edited the AppLovinProcessGradleBuildFile class and set the version number from "+" to "5.6.6". This forced the build to use the correct version, and everything worked as expected.

However, when I change the version string back to "+", it automatically reverts to v5.6.4 during the build process. I’m not sure why it fails to pull the latest version.

I’ve submitted a hotfix now for my app, so the issue is hopefully resolved for now. Still, I’d appreciate understanding how to make the Unity package consistently use the latest version.

**Comment by NanaAmoah** [comment]
@JimRaid We haven't been able to reproduce the issue you reported. Could you try clearing the library and/or Gradle cache to see if that fixes the issue?
If it doesn't, could you try reproducing the issue in our demo app [here](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin) and sharing the modified project with us so we can investigate further?
