### ISSUE TITLE
App crashes on some device

### ISSUE THREAD

**Issue by ltsadevs** [AppLovin/AppLovin-MAX-SDK-Android#88]
App crashes on some devices.

`E/AppLovinSdk: [Utils] Failed to process version string.
    java.lang.NumberFormatException: Invalid int: ""
        at java.lang.Integer.invalidInt(Integer.java:138)
        at java.lang.Integer.parseInt(Integer.java:358)
        at java.lang.Integer.parseInt(Integer.java:334)
        at com.applovin.impl.sdk.utils.Utils.compare(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.b.a.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.b.b.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.b.b.<init>(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.a.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.b.a$1.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.b.a$1.a(Unknown Source)
        at com.applovin.impl.sdk.e.u$1.a(Unknown Source)
        at com.applovin.impl.sdk.network.b.a(Unknown Source)
        at com.applovin.impl.sdk.e.u.run(Unknown Source)
        at com.applovin.impl.sdk.e.o.a(Unknown Source)
        at com.applovin.impl.mediation.debugger.b.a.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)`

I have not found any other error message for the crash.

**Comment by ltsadevs** [comment]
Also the eCPM is way too low, $0.10-$0.12. Is this normal eCPM in Applovin? Mopub was providing better eCPM.

**Comment by thomasmso** [comment]
> crash
@christophercong can assist you there - it's just a log on our end and your app shouldn't be crashing/exiting right? It should be isolated to your development builds only.

> eCPM
CPMs are a function of many factors - we advise adding more networks into your monetization stack to maximize CPMs.

**Comment by ltsadevs** [comment]
Hi @thomasmso, I am talking about Applovin network. Applovin Exchange showing $0.03 eCPM.

**Comment by thomasmso** [comment]
@ltsadevs - Did you have other networks integrated for native ads? Could you send me an email at thomas.so@applovin.com we can debug your integration deeper there.

**Comment by christophercong** [comment]
Hi @ltsadevs, the log you provided is an error log and not a crash. Regardless, the error will be fixed in the next release.

**Comment by christophercong** [comment]
Hi @Itsdev, we just released Android SDK v11.1.0 with the fix.

**Comment by vishnusp** [comment]
@thomasmso @ltsadevs I also face the same behaviour with eCPM and fill rates. MoPub had better fill rates and eCPM. Here, even when other network has higher eCPM most of the impressions are for AppLovin which has very low eCPM. With MoPub, Fb ads were filling properly and was giving good number of impressions, but MAX is not filling Fb Banner and MRec ads. MaX Seems to be a biased mediation for me. I mailed MAX dev team, but no response!

**Comment by taugin** [comment]
> @thomasmso @ltsadevs I also face the same behaviour with eCPM and fill rates. MoPub had better fill rates and eCPM. Here, even when other network has higher eCPM most of the impressions are for AppLovin which has very low eCPM. With MoPub, Fb ads were filling properly and was giving good number of impressions, but MAX is not filling Fb Banner and MRec ads. MaX Seems to be a biased mediation for me. I mailed MAX dev team, but no response!

I also have the same issue.

**Comment by thomasmso** [comment]
Hey @vishnusp & @taugin -

That usually implies too sparse a waterfall if our share goes up like that so you want to make it more competitive to spread it out more and increase demand. I'd recommend adding more high-yielding networks like Facebook/AdMob, and depending on your audience, regional networks that we support as well.

**Comment by vishnusp** [comment]
@thomasmso that doesn't seem true. I was already using Facebook ads in MAX mediation, but I  was getting no fill most of the time. So integrated FB ads directly and I'm always getting fill. And With MAX majority impressions are for AppLovin only even though it has the lowest eCpm. So I decided to move out of MAX. Really sad to see such a good platform MoPub being destroyed like this!

**Comment by thomasmso** [comment]
Sorry to hear you feel that way. Our product works best when you have multiple demand sources competing in an auction. We support 25+ networks across different ad formats. If you want to learn more about how to optimize your setup on MAX, please reach out to partner_support@applovin.com. We have a dedicated person to help.

**Comment by ltsadevs** [comment]
"dedicated person" ????? Seriously? Already sent several follow up emails to this support email as well as to your email. Got no response. God bless you and your customer acquisition strategies. I am done with MAX. And thanks for destroying MoPub.
