### ISSUE TITLE
Crash on load banner ads

### ISSUE THREAD

**Issue by adierebel** [AppLovin/AppLovin-MAX-SDK-Android#89]
My app crash when load ads

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.applovin.impl.mediation.e.a(Unknown Source:14)
        at com.applovin.impl.mediation.MediationServiceImpl.collectSignal(Unknown Source:28)
        at com.applovin.impl.mediation.b.b$2.run(Unknown Source:26)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8276)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

SDK Logs:

```
========================================
=====AppLovin SDK=====
===SDK Versions===
Version: 10.3.5
Plugin Version: 
Ad Review Version: 4.1.3
===Device Info===
OS: 11 (R - API 30)
GAID: <Enable verbose logging to see the GAID to use for test devices - https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK>
Model: RMX1971
Locale: en_US
Emulator: false
WVVC: null
Tablet: false
===App Info===
Application ID: ****
Target SDK: 31
ExoPlayer Version: -1
===SDK Settings===
SDK Key: ****
Mediation Provider: max
TG: 98
Test Mode On: true
Verbose Logging On: false
===Privacy States===
Please review AppLovin MAX documentation to be compliant with regional privacy policies.

Age Restricted User - No value set
Has User Consent - No value set
"Do Not Sell" - No value set
========================================
```

```kotlin
// Init SDK & load banner
AppLovinSdk.getInstance( this ).mediationProvider = "max"
AppLovinSdk.getInstance( this ).initializeSdk {
  viewMain.mainAdsBanner.setListener(object : MaxAdViewAdListener {
      override fun onAdLoaded(ad: MaxAd?) {
          viewMain.containerAds.visibility = View.VISIBLE
      }

      override fun onAdDisplayed(ad: MaxAd?) { }

      override fun onAdClicked(ad: MaxAd?) { }

      override fun onAdLoadFailed(adUnitId: String?, error: MaxError?) { }

      override fun onAdExpanded(ad: MaxAd?) { }

      override fun onAdCollapsed(ad: MaxAd?) { }

      override fun onAdDisplayFailed(ad: MaxAd?, error: MaxError?) { }

      override fun onAdHidden(ad: MaxAd?) { }
  })
  viewMain.mainAdsBanner.loadAd()
}
```

**Comment by thomasmso** [comment]
Hey there - this crash has been resolved through a server-side update, please let us know if it persists. Thanks!
