### ISSUE TITLE
Can not to load test ADs: mediation.a.d cannot be cast to mediation.a.b

### ISSUE THREAD

**Issue by Zozulinsky** [AppLovin/AppLovin-MAX-SDK-Android#98]
I tried to test the Aplovin MAX banner ads , but without success. I did the same thing as the example at ProgrammaticBannerAdActivity 
Also i see in the logs: 
```
2022-01-19 15:44:14.779 E: [TaskFetchMediatedAd 56a439aa82c7a834] Ad format requested does not match ad unit id's format.
2022-01-19 15:44:16.445 E: [ListenerCallbackInvoker] Unable to notify ad event listener about ad being loaded
    java.lang.ClassCastException: com.applovin.impl.mediation.a.d cannot be cast to com.applovin.impl.mediation.a.b
        at com.applovin.impl.mediation.ads.MaxAdViewImpl$a.onAdLoaded(Unknown Source:61)
        at com.applovin.impl.mediation.d$a.onAdLoaded(Unknown Source:49)
        at com.applovin.impl.sdk.utils.i$7.run(Unknown Source:4)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:8)
        at com.applovin.impl.sdk.utils.i.a(Unknown Source:9)
        at com.applovin.impl.sdk.utils.i.a(Unknown Source:1)
        at com.applovin.impl.mediation.b.e.a(Unknown Source:141)
        at com.applovin.impl.mediation.b.e.a(Unknown Source:0)
        at com.applovin.impl.mediation.b.e$a$1.onAdLoaded(Unknown Source:113)
        at com.applovin.impl.sdk.utils.i$7.run(Unknown Source:4)
        at com.applovin.sdk.AppLovinSdkUtils.runOnUiThread(Unknown Source:8)
        at com.applovin.impl.sdk.utils.i.a(Unknown Source:9)
        at com.applovin.impl.sdk.utils.i.a(Unknown Source:1)
        at com.applovin.impl.mediation.MediationServiceImpl$a.a(Unknown Source:19)
        at com.applovin.impl.mediation.g$a$1.run(Unknown Source:32)
        at com.applovin.impl.mediation.g$a$14.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by joeapplovin** [comment]
Hi @Zozulinsky - the error message suggests that the ad unit you're using may not be of the banner format.  Can you please confirm that you've selected banner during the [ad unit creation process](https://dash.applovin.com/documentation/mediation/max/integrate)?

**Comment by Zozulinsky** [comment]
Oh.. I used wrong unit id. Thank you!

**Comment by joeapplovin** [comment]
Glad to help!
